//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.KhoSoi
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUDIT_NL_DMPHIEU
    {
        public Nullable<decimal> STT { get; set; }
        public string MAPHIEU { get; set; }
        public Nullable<System.DateTime> NGAYYC { get; set; }
        public string NGUOIPD { get; set; }
        public string NGUOIXX { get; set; }
        public string NGUOITIEPNHAN { get; set; }
        public string NGUOILAPPHIEU { get; set; }
        public string LYDOSD { get; set; }
        public string MAPHIEUPD { get; set; }
        public string LOAIPHIEU { get; set; }
        public Nullable<byte> DX { get; set; }
        public Nullable<byte> NK { get; set; }
        public Nullable<byte> ND { get; set; }
        public Nullable<byte> KH { get; set; }
        public Nullable<bool> HIEULUC { get; set; }
        public Nullable<System.DateTime> NGAYXX { get; set; }
        public Nullable<System.DateTime> NGAYPD { get; set; }
        public Nullable<System.DateTime> NGAYTN { get; set; }
        public Nullable<byte> XXET { get; set; }
        public Nullable<byte> PDUYET { get; set; }
        public Nullable<byte> TNHANYC { get; set; }
        public string HANHDONG { get; set; }
        public string HOSTNAME { get; set; }
        public Nullable<System.DateTime> NGAYSUA { get; set; }
    }
}
