//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.KhoSoi
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONHANGGCSOI_CT
    {
        public string MADH_GCSOI { get; set; }
        public string Loaidh { get; set; }
        public Nullable<System.DateTime> NGAYYCAU { get; set; }
        public Nullable<System.DateTime> NGAYKETTHUC { get; set; }
        public string DIENGIAI { get; set; }
        public Nullable<decimal> SOLUONGYEUCAU { get; set; }
        public string MASOITHANHPHAM { get; set; }
        public System.Guid KHOA_ID { get; set; }
    }
}
