//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.KhoSoi
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVOICE
    {
        public string MAPHIEU { get; set; }
        public string MAPHIEUPD { get; set; }
        public string SOHOPDONG { get; set; }
        public string MAVATTU { get; set; }
        public string TENVT { get; set; }
        public string INVOICE1 { get; set; }
        public string TOKHAI { get; set; }
        public Nullable<decimal> GIANHAP { get; set; }
        public string QUOCGIA { get; set; }
        public Nullable<System.DateTime> NGAYNHAPHANG { get; set; }
        public string MASPKHACH { get; set; }
        public string MAKH { get; set; }
        public string MANVCAPNHAT { get; set; }
        public Nullable<System.DateTime> NGAYCAPNHAT { get; set; }
        public string MANVMODIFY { get; set; }
        public Nullable<System.DateTime> NGAYMODIFY { get; set; }
        public System.Guid khoa_id { get; set; }
    }
}
