//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.KhoSoi
{
    using System;
    using System.Collections.Generic;
    
    public partial class NL_CHATLUONGKIEMTRA
    {
        public string SOCTXN { get; set; }
        public string MAVT { get; set; }
        public string HIEU { get; set; }
        public string LO { get; set; }
        public string MAPHIEUPD { get; set; }
        public decimal THUC { get; set; }
        public string KHOKIEMTRA { get; set; }
        public string DONVIKIEMTRA { get; set; }
        public string MANVKHO { get; set; }
        public string MANVDONVI { get; set; }
        public string LOAI { get; set; }
        public string NHACC { get; set; }
        public string DANGLOI { get; set; }
        public string MANHACC { get; set; }
    }
}
