//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.KhoSoi
{
    using System;
    using System.Collections.Generic;
    
    public partial class NL_CTPHIEU
    {
        public string MASOCP { get; set; }
        public string MAPHIEU { get; set; }
        public string MAVT { get; set; }
        public Nullable<decimal> SLYCAU { get; set; }
        public Nullable<decimal> SLXXET { get; set; }
        public Nullable<decimal> SLPD { get; set; }
        public Nullable<decimal> SLTONDVI { get; set; }
        public string TINHTRANG { get; set; }
        public Nullable<System.DateTime> THOIDIEMSD { get; set; }
        public string GHICHU { get; set; }
        public string LO { get; set; }
        public string HIEU { get; set; }
        public Nullable<System.DateTime> NGAYDAPUNG { get; set; }
        public string KHOATHAMCHIEU { get; set; }
        public bool NK_STATIC { get; set; }
        public string IDMaDV_YCMUA { get; set; }
        public string LOAIYEUCAU { get; set; }
        public string GhiChucuaLanhDao { get; set; }
        public string MADH { get; set; }
        public string DonviTH { get; set; }
        public string Thang { get; set; }
        public string Nam { get; set; }
        public Nullable<decimal> SLTONCTY { get; set; }
    
        public virtual NL_DMPHIEU NL_DMPHIEU { get; set; }
        public virtual NL_DMNHACCAP NL_DMNHACCAP { get; set; }
        public virtual NL_DMNHACCAP NL_DMNHACCAP1 { get; set; }
        public virtual TBLDMNGUYENLIEU TBLDMNGUYENLIEU { get; set; }
    }
}
