//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.KhoSoi
{
    using System;
    using System.Collections.Generic;
    
    public partial class NL_CTXUATNHAP_Vtest
    {
        public string KHOAKEYXN { get; set; }
        public string MAVT { get; set; }
        public string HIEU { get; set; }
        public string LO { get; set; }
        public string MADH { get; set; }
        public string LANXN { get; set; }
        public decimal SOLUONGYC { get; set; }
        public decimal SOLUONGTT { get; set; }
        public string MAPHIEUPD { get; set; }
        public string GHICHU { get; set; }
        public string LOAICAPPHAT { get; set; }
        public string SOCTXN { get; set; }
        public System.DateTime NGAYKETOAN { get; set; }
        public string MAVTTAM { get; set; }
        public string MaTaiSan { get; set; }
        public Nullable<decimal> DonGia { get; set; }
        public byte DAXUATKHO { get; set; }
        public Nullable<System.DateTime> MODIFIED { get; set; }
        public string SOHOADON { get; set; }
        public string KHOATHAMCHIEU { get; set; }
        public bool NK_STATIC { get; set; }
        public string LOAIDONHANG { get; set; }
        public System.Guid ID_XN { get; set; }
        public string MADINHMUC { get; set; }
    }
}
