//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.KhoSoi
{
    using System;
    using System.Collections.Generic;
    
    public partial class NL_CTPHIEUNHAP_CHUYEN
    {
        public string SOCTXUAT { get; set; }
        public string SOCTNHAP { get; set; }
        public string MAVT { get; set; }
        public string HIEU { get; set; }
        public string LO { get; set; }
        public string MADH { get; set; }
        public string LANXN { get; set; }
        public Nullable<decimal> SOLUONGXUAT { get; set; }
        public string GHICHU { get; set; }
        public Nullable<System.DateTime> NGAYCN { get; set; }
        public string MANVCN { get; set; }
        public System.Guid id_kHOA { get; set; }
    }
}
