//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.KhoSoi
{
    using System;
    using System.Collections.Generic;
    
    public partial class NL_DMKHO
    {
        public string MAKHO { get; set; }
        public string TENKHO { get; set; }
        public string GHICHU { get; set; }
        public string MADV { get; set; }
        public string NOIDEN { get; set; }
        public string DIACHI { get; set; }
        public Nullable<bool> Hieuluc { get; set; }
        public string Nguoinhan { get; set; }
    }
}
