//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.KhoSoi
{
    using System;
    using System.Collections.Generic;
    
    public partial class NL_DMNHACCAP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NL_DMNHACCAP()
        {
            this.NL_CTPHIEU = new HashSet<NL_CTPHIEU>();
            this.NL_CTPHIEU1 = new HashSet<NL_CTPHIEU>();
            this.NL_CTXUATNHAP = new HashSet<NL_CTXUATNHAP>();
        }
    
        public string HIEU { get; set; }
        public string MANHACC { get; set; }
        public string TENNHACC { get; set; }
        public string DIACHI { get; set; }
        public Nullable<float> DIENTHOAI { get; set; }
        public string EMAIL { get; set; }
        public bool HIEULUC { get; set; }
        public string XUATXU { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NL_CTPHIEU> NL_CTPHIEU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NL_CTPHIEU> NL_CTPHIEU1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NL_CTXUATNHAP> NL_CTXUATNHAP { get; set; }
    }
}
