//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.KhoSoi
{
    using System;
    using System.Collections.Generic;
    
    public partial class NL_DMPHIEUNHAP_CHUYEN
    {
        public string SOCTNHAP { get; set; }
        public string SOCTXUAT { get; set; }
        public string MADH { get; set; }
        public string MAHTHUC { get; set; }
        public string MAKHOXUAT { get; set; }
        public string MAKHONHAN { get; set; }
        public string MANVXUAT { get; set; }
        public string MANVNHAN { get; set; }
        public string NOINHAN { get; set; }
        public string NOIDEN { get; set; }
        public string GHICHU { get; set; }
        public Nullable<System.DateTime> NGAYCN { get; set; }
    }
}
