//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.KhoSoi
{
    using System;
    using System.Collections.Generic;
    
    public partial class NL_DMHINHTHUC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NL_DMHINHTHUC()
        {
            this.NL_DMPHIEUXN = new HashSet<NL_DMPHIEUXN>();
        }
    
        public string MAHTHUC { get; set; }
        public string TENHTHUC { get; set; }
        public string GHICHU { get; set; }
        public byte HIEULUC { get; set; }
        public Nullable<bool> GCSOI { get; set; }
        public Nullable<bool> GCDUCBONG { get; set; }
        public Nullable<bool> KIEMTRACHATLUONG { get; set; }
        public string XUAT3BUOC { get; set; }
        public string Account_KT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NL_DMPHIEUXN> NL_DMPHIEUXN { get; set; }
    }
}
