//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.KhoSoi
{
    using System;
    using System.Collections.Generic;
    
    public partial class NL_DMNHOMNGLIEU
    {
        public string MANGL { get; set; }
        public string MANHOMNGL { get; set; }
        public string TENNHOMNGL { get; set; }
        public string MANHOMVT { get; set; }
        public string MANHOMSOI { get; set; }
        public string MATC { get; set; }
        public string KyhieuThanhPhan { get; set; }
        public string TENNHOMCHITIET { get; set; }
    }
}
