//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.KhoSoi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class wqlkhosoiEntities : DbContext
    {
        public wqlkhosoiEntities()
            : base("name=wqlkhosoiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<QLKhoSoi_Menu> QLKhoSoi_Menu { get; set; }
        public virtual DbSet<QLKhoSoi_Role> QLKhoSoi_Role { get; set; }
        public virtual DbSet<QLKhoSoi_User> QLKhoSoi_User { get; set; }
        public virtual DbSet<QLKhoSoi_User_Page> QLKhoSoi_User_Page { get; set; }
        public virtual DbSet<QLKhoSoi_User_Role> QLKhoSoi_User_Role { get; set; }
        public virtual DbSet<NL_CTPHIEU> NL_CTPHIEU { get; set; }
        public virtual DbSet<NL_DMPHIEU> NL_DMPHIEU { get; set; }
        public virtual DbSet<NL_DMloaidonhang> NL_DMloaidonhang { get; set; }
        public virtual DbSet<Tbl_SoPYCXuatSoi> Tbl_SoPYCXuatSoi { get; set; }
        public virtual DbSet<QLKhoSoi_Page> QLKhoSoi_Page { get; set; }
        public virtual DbSet<NL_DMKHO> NL_DMKHO { get; set; }
        public virtual DbSet<NL_DMNHACCAP> NL_DMNHACCAP { get; set; }
        public virtual DbSet<NL_CTPHIEUNHAP_CHUYEN> NL_CTPHIEUNHAP_CHUYEN { get; set; }
        public virtual DbSet<NL_DMPHIEUNHAP_CHUYEN> NL_DMPHIEUNHAP_CHUYEN { get; set; }
        public virtual DbSet<NL_DMHINHTHUC> NL_DMHINHTHUC { get; set; }
        public virtual DbSet<DONHANGGCSOI> DONHANGGCSOIs { get; set; }
        public virtual DbSet<DONHANGGCSOI_CT> DONHANGGCSOI_CT { get; set; }
        public virtual DbSet<NL_CHATLUONGKIEMTRA> NL_CHATLUONGKIEMTRA { get; set; }
        public virtual DbSet<GC_CTPHIEUXUATGC> GC_CTPHIEUXUATGC { get; set; }
        public virtual DbSet<GC_DMPHIEU_BANGKENHAPSOI> GC_DMPHIEU_BANGKENHAPSOI { get; set; }
        public virtual DbSet<AUDIT_NL_DMPHIEU> AUDIT_NL_DMPHIEU { get; set; }
        public virtual DbSet<NL_DMNHOMNGLIEU> NL_DMNHOMNGLIEU { get; set; }
        public virtual DbSet<NL_DMPHIEUXN> NL_DMPHIEUXN { get; set; }
        public virtual DbSet<TBLDMNGUYENLIEU> TBLDMNGUYENLIEUx { get; set; }
        public virtual DbSet<INVOICE> INVOICEs { get; set; }
        public virtual DbSet<NL_CTXUATNHAP> NL_CTXUATNHAP { get; set; }
        public virtual DbSet<NHAPDIENGIAI_SOI> NHAPDIENGIAI_SOI { get; set; }
    
        public virtual ObjectResult<SP_NL_CTPHIEU_LOADBYMAPHIEU_Result> SP_NL_CTPHIEU_LOADBYMAPHIEU(string mAPHIEU, string userID)
        {
            var mAPHIEUParameter = mAPHIEU != null ?
                new ObjectParameter("MAPHIEU", mAPHIEU) :
                new ObjectParameter("MAPHIEU", typeof(string));
    
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_NL_CTPHIEU_LOADBYMAPHIEU_Result>("SP_NL_CTPHIEU_LOADBYMAPHIEU", mAPHIEUParameter, userIDParameter);
        }
    
        public virtual ObjectResult<string> SP_LOAD_MAPHIEU_YEUCAU_HIEUCHINH(string nGUOILAPPHIEU)
        {
            var nGUOILAPPHIEUParameter = nGUOILAPPHIEU != null ?
                new ObjectParameter("NGUOILAPPHIEU", nGUOILAPPHIEU) :
                new ObjectParameter("NGUOILAPPHIEU", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_LOAD_MAPHIEU_YEUCAU_HIEUCHINH", nGUOILAPPHIEUParameter);
        }
    
        public virtual ObjectResult<string> SP_LOAD_MAPHIEU_YEUCAU_PHEDUYET(string nGUOIPDUYET)
        {
            var nGUOIPDUYETParameter = nGUOIPDUYET != null ?
                new ObjectParameter("NGUOIPDUYET", nGUOIPDUYET) :
                new ObjectParameter("NGUOIPDUYET", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_LOAD_MAPHIEU_YEUCAU_PHEDUYET", nGUOIPDUYETParameter);
        }
    
        public virtual ObjectResult<string> SP_LOAD_MAPHIEU_YEUCAU_XEMXET(string nGUOIXXET)
        {
            var nGUOIXXETParameter = nGUOIXXET != null ?
                new ObjectParameter("NGUOIXXET", nGUOIXXET) :
                new ObjectParameter("NGUOIXXET", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_LOAD_MAPHIEU_YEUCAU_XEMXET", nGUOIXXETParameter);
        }
    
        public virtual ObjectResult<SP_LOAD_DANHMUCSOI_2023_Result> SP_LOAD_DANHMUCSOI_2023(string mAVATTU)
        {
            var mAVATTUParameter = mAVATTU != null ?
                new ObjectParameter("MAVATTU", mAVATTU) :
                new ObjectParameter("MAVATTU", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_LOAD_DANHMUCSOI_2023_Result>("SP_LOAD_DANHMUCSOI_2023", mAVATTUParameter);
        }
    
        public virtual ObjectResult<SP_TAOMAPHIEUYEUCAUMUAHANG_Result> SP_TAOMAPHIEUYEUCAUMUAHANG(string kIHIEU)
        {
            var kIHIEUParameter = kIHIEU != null ?
                new ObjectParameter("KIHIEU", kIHIEU) :
                new ObjectParameter("KIHIEU", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TAOMAPHIEUYEUCAUMUAHANG_Result>("SP_TAOMAPHIEUYEUCAUMUAHANG", kIHIEUParameter);
        }
    
        public virtual ObjectResult<sp_Load_NL_DMloaidonhang_2023_Result> sp_Load_NL_DMloaidonhang_2023()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Load_NL_DMloaidonhang_2023_Result>("sp_Load_NL_DMloaidonhang_2023");
        }
    
        public virtual ObjectResult<sp_Load_NL_DMNHACCAP_2023_Result> sp_Load_NL_DMNHACCAP_2023()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Load_NL_DMNHACCAP_2023_Result>("sp_Load_NL_DMNHACCAP_2023");
        }
    
        public virtual ObjectResult<spLoad_NL_DMYEUCAU_ByLoaidonhang_Result> spLoad_NL_DMYEUCAU_ByLoaidonhang(string lOAIDONHANG)
        {
            var lOAIDONHANGParameter = lOAIDONHANG != null ?
                new ObjectParameter("LOAIDONHANG", lOAIDONHANG) :
                new ObjectParameter("LOAIDONHANG", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spLoad_NL_DMYEUCAU_ByLoaidonhang_Result>("spLoad_NL_DMYEUCAU_ByLoaidonhang", lOAIDONHANGParameter);
        }
    
        public virtual ObjectResult<Sp_API_Load_NLDMPhieu_Result> Sp_API_Load_NLDMPhieu(string maphieu)
        {
            var maphieuParameter = maphieu != null ?
                new ObjectParameter("maphieu", maphieu) :
                new ObjectParameter("maphieu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_API_Load_NLDMPhieu_Result>("Sp_API_Load_NLDMPhieu", maphieuParameter);
        }
    
        public virtual ObjectResult<SP_PHIEUYEUCAUXUATKHO_LOAD_MAKHO_Result> SP_PHIEUYEUCAUXUATKHO_LOAD_MAKHO(string kYHIEU, string mANV)
        {
            var kYHIEUParameter = kYHIEU != null ?
                new ObjectParameter("KYHIEU", kYHIEU) :
                new ObjectParameter("KYHIEU", typeof(string));
    
            var mANVParameter = mANV != null ?
                new ObjectParameter("MANV", mANV) :
                new ObjectParameter("MANV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_PHIEUYEUCAUXUATKHO_LOAD_MAKHO_Result>("SP_PHIEUYEUCAUXUATKHO_LOAD_MAKHO", kYHIEUParameter, mANVParameter);
        }
    
        public virtual ObjectResult<SP_LOADMAHINHTHUCYEUCAUXUAT_Result> SP_LOADMAHINHTHUCYEUCAUXUAT(string kIHIEUDV)
        {
            var kIHIEUDVParameter = kIHIEUDV != null ?
                new ObjectParameter("KIHIEUDV", kIHIEUDV) :
                new ObjectParameter("KIHIEUDV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_LOADMAHINHTHUCYEUCAUXUAT_Result>("SP_LOADMAHINHTHUCYEUCAUXUAT", kIHIEUDVParameter);
        }
    
        public virtual ObjectResult<SP_LOAD_DATA_MASOI_XD_Result> SP_LOAD_DATA_MASOI_XD(string mAKHO)
        {
            var mAKHOParameter = mAKHO != null ?
                new ObjectParameter("MAKHO", mAKHO) :
                new ObjectParameter("MAKHO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_LOAD_DATA_MASOI_XD_Result>("SP_LOAD_DATA_MASOI_XD", mAKHOParameter);
        }
    
        public virtual ObjectResult<SP_LOAD_MAHTHUC_PHIEUYEUCAUXUATKHO_XD_Result> SP_LOAD_MAHTHUC_PHIEUYEUCAUXUATKHO_XD(string kIHIEU)
        {
            var kIHIEUParameter = kIHIEU != null ?
                new ObjectParameter("KIHIEU", kIHIEU) :
                new ObjectParameter("KIHIEU", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_LOAD_MAHTHUC_PHIEUYEUCAUXUATKHO_XD_Result>("SP_LOAD_MAHTHUC_PHIEUYEUCAUXUATKHO_XD", kIHIEUParameter);
        }
    
        public virtual ObjectResult<SP_Load_MaPhieuYCXuatSoi_Result> SP_Load_MaPhieuYCXuatSoi(string key, string kihieu)
        {
            var keyParameter = key != null ?
                new ObjectParameter("key", key) :
                new ObjectParameter("key", typeof(string));
    
            var kihieuParameter = kihieu != null ?
                new ObjectParameter("kihieu", kihieu) :
                new ObjectParameter("kihieu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Load_MaPhieuYCXuatSoi_Result>("SP_Load_MaPhieuYCXuatSoi", keyParameter, kihieuParameter);
        }
    
        public virtual ObjectResult<SP_VATTU_YC_XUATSOI_Result> SP_VATTU_YC_XUATSOI(string mAKHO)
        {
            var mAKHOParameter = mAKHO != null ?
                new ObjectParameter("MAKHO", mAKHO) :
                new ObjectParameter("MAKHO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_VATTU_YC_XUATSOI_Result>("SP_VATTU_YC_XUATSOI", mAKHOParameter);
        }
    
        public virtual int SP_RPT_NL_PHIEUYCXUATVT(string sOCTXN)
        {
            var sOCTXNParameter = sOCTXN != null ?
                new ObjectParameter("SOCTXN", sOCTXN) :
                new ObjectParameter("SOCTXN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_RPT_NL_PHIEUYCXUATVT", sOCTXNParameter);
        }
    
        public virtual ObjectResult<SP_RPT_NL_PYC_XUATVT_Result> SP_RPT_NL_PYC_XUATVT(string sOCTXN)
        {
            var sOCTXNParameter = sOCTXN != null ?
                new ObjectParameter("SOCTXN", sOCTXN) :
                new ObjectParameter("SOCTXN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_RPT_NL_PYC_XUATVT_Result>("SP_RPT_NL_PYC_XUATVT", sOCTXNParameter);
        }
    
        public virtual ObjectResult<LOAD_MADONHANG_ND_XK_Result> LOAD_MADONHANG_ND_XK(string mADH)
        {
            var mADHParameter = mADH != null ?
                new ObjectParameter("MADH", mADH) :
                new ObjectParameter("MADH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LOAD_MADONHANG_ND_XK_Result>("LOAD_MADONHANG_ND_XK", mADHParameter);
        }
    
        public virtual ObjectResult<SP_NL_LOADDMHINHTHUC_NHAPKHOTHUKHO_Result> SP_NL_LOADDMHINHTHUC_NHAPKHOTHUKHO()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_NL_LOADDMHINHTHUC_NHAPKHOTHUKHO_Result>("SP_NL_LOADDMHINHTHUC_NHAPKHOTHUKHO");
        }
    
        public virtual ObjectResult<string> SP_NL_TAOSOCHUNGTU(string mAHINHTHUC)
        {
            var mAHINHTHUCParameter = mAHINHTHUC != null ?
                new ObjectParameter("MAHINHTHUC", mAHINHTHUC) :
                new ObjectParameter("MAHINHTHUC", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_NL_TAOSOCHUNGTU", mAHINHTHUCParameter);
        }
    
        public virtual ObjectResult<SP_MAKHOBYMANV_LOAD_Result> SP_MAKHOBYMANV_LOAD(string mANV)
        {
            var mANVParameter = mANV != null ?
                new ObjectParameter("MANV", mANV) :
                new ObjectParameter("MANV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MAKHOBYMANV_LOAD_Result>("SP_MAKHOBYMANV_LOAD", mANVParameter);
        }
    
        public virtual int SP_NL_DELETE_KHONGCHITIET_XUATNHAP(string mANV)
        {
            var mANVParameter = mANV != null ?
                new ObjectParameter("MANV", mANV) :
                new ObjectParameter("MANV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_NL_DELETE_KHONGCHITIET_XUATNHAP", mANVParameter);
        }
    
        public virtual int LOAD_DATA_MASOI_NHAPKHO_NKNB_XBAN_XGC(string nOIDEN, string mAHTHUC)
        {
            var nOIDENParameter = nOIDEN != null ?
                new ObjectParameter("NOIDEN", nOIDEN) :
                new ObjectParameter("NOIDEN", typeof(string));
    
            var mAHTHUCParameter = mAHTHUC != null ?
                new ObjectParameter("MAHTHUC", mAHTHUC) :
                new ObjectParameter("MAHTHUC", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LOAD_DATA_MASOI_NHAPKHO_NKNB_XBAN_XGC", nOIDENParameter, mAHTHUCParameter);
        }
    
        public virtual ObjectResult<LOAD_DATA_MASOI_NHAPKHO_NKNB_XBAN_XGC_v1_Result> LOAD_DATA_MASOI_NHAPKHO_NKNB_XBAN_XGC_v1(string nOIDEN, string mAHTHUC)
        {
            var nOIDENParameter = nOIDEN != null ?
                new ObjectParameter("NOIDEN", nOIDEN) :
                new ObjectParameter("NOIDEN", typeof(string));
    
            var mAHTHUCParameter = mAHTHUC != null ?
                new ObjectParameter("MAHTHUC", mAHTHUC) :
                new ObjectParameter("MAHTHUC", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LOAD_DATA_MASOI_NHAPKHO_NKNB_XBAN_XGC_v1_Result>("LOAD_DATA_MASOI_NHAPKHO_NKNB_XBAN_XGC_v1", nOIDENParameter, mAHTHUCParameter);
        }
    
        public virtual ObjectResult<SP_NHAPKHOTHEOPHIEUPHEDUYET_MAVT_Result> SP_NHAPKHOTHEOPHIEUPHEDUYET_MAVT(string mAKHO)
        {
            var mAKHOParameter = mAKHO != null ?
                new ObjectParameter("MAKHO", mAKHO) :
                new ObjectParameter("MAKHO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_NHAPKHOTHEOPHIEUPHEDUYET_MAVT_Result>("SP_NHAPKHOTHEOPHIEUPHEDUYET_MAVT", mAKHOParameter);
        }
    
        public virtual ObjectResult<SP_LOAD_NL_DMLO_BY_HIEU_Result> SP_LOAD_NL_DMLO_BY_HIEU(string hIEU)
        {
            var hIEUParameter = hIEU != null ?
                new ObjectParameter("HIEU", hIEU) :
                new ObjectParameter("HIEU", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_LOAD_NL_DMLO_BY_HIEU_Result>("SP_LOAD_NL_DMLO_BY_HIEU", hIEUParameter);
        }
    
        public virtual ObjectResult<SP_LOAD_NL_DMLO_BY_HIEU_GC_CTPHIEUXUATNHAP_Result> SP_LOAD_NL_DMLO_BY_HIEU_GC_CTPHIEUXUATNHAP(string hIEU)
        {
            var hIEUParameter = hIEU != null ?
                new ObjectParameter("HIEU", hIEU) :
                new ObjectParameter("HIEU", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_LOAD_NL_DMLO_BY_HIEU_GC_CTPHIEUXUATNHAP_Result>("SP_LOAD_NL_DMLO_BY_HIEU_GC_CTPHIEUXUATNHAP", hIEUParameter);
        }
    
        public virtual ObjectResult<SP_LOAD_HINHTHUC_XUATKHO_THUKHO_Result> SP_LOAD_HINHTHUC_XUATKHO_THUKHO()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_LOAD_HINHTHUC_XUATKHO_THUKHO_Result>("SP_LOAD_HINHTHUC_XUATKHO_THUKHO");
        }
    
        public virtual ObjectResult<Sp_Load_SOCTXN_XD1_XD2_XuatChuyenSX_Result> Sp_Load_SOCTXN_XD1_XD2_XuatChuyenSX(string manv, string key)
        {
            var manvParameter = manv != null ?
                new ObjectParameter("manv", manv) :
                new ObjectParameter("manv", typeof(string));
    
            var keyParameter = key != null ?
                new ObjectParameter("key", key) :
                new ObjectParameter("key", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Load_SOCTXN_XD1_XD2_XuatChuyenSX_Result>("Sp_Load_SOCTXN_XD1_XD2_XuatChuyenSX", manvParameter, keyParameter);
        }
    
        public virtual int SP_UPDATE_GUIAPI_TBLDMNGUYENLIEU(string mAVT)
        {
            var mAVTParameter = mAVT != null ?
                new ObjectParameter("MAVT", mAVT) :
                new ObjectParameter("MAVT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPDATE_GUIAPI_TBLDMNGUYENLIEU", mAVTParameter);
        }
    
        public virtual ObjectResult<Sp_Load_SOCTXN_XD1_XD2_CTXuatChuyenSX_Result> Sp_Load_SOCTXN_XD1_XD2_CTXuatChuyenSX(string soctxn)
        {
            var soctxnParameter = soctxn != null ?
                new ObjectParameter("soctxn", soctxn) :
                new ObjectParameter("soctxn", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Load_SOCTXN_XD1_XD2_CTXuatChuyenSX_Result>("Sp_Load_SOCTXN_XD1_XD2_CTXuatChuyenSX", soctxnParameter);
        }
    
        public virtual int ADD_MASOI_NHAPKHO_SANXUAT(string mANVNHAN, string soctxn)
        {
            var mANVNHANParameter = mANVNHAN != null ?
                new ObjectParameter("MANVNHAN", mANVNHAN) :
                new ObjectParameter("MANVNHAN", typeof(string));
    
            var soctxnParameter = soctxn != null ?
                new ObjectParameter("soctxn", soctxn) :
                new ObjectParameter("soctxn", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ADD_MASOI_NHAPKHO_SANXUAT", mANVNHANParameter, soctxnParameter);
        }
    
        public virtual int Delete_MASOI_NHAPKHO_SANXUAT(string mANVNHAN, string soctxn)
        {
            var mANVNHANParameter = mANVNHAN != null ?
                new ObjectParameter("MANVNHAN", mANVNHAN) :
                new ObjectParameter("MANVNHAN", typeof(string));
    
            var soctxnParameter = soctxn != null ?
                new ObjectParameter("soctxn", soctxn) :
                new ObjectParameter("soctxn", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_MASOI_NHAPKHO_SANXUAT", mANVNHANParameter, soctxnParameter);
        }
    
        public virtual ObjectResult<DANHMUC_KHO_NOIDEN_XUATKHO_Result> DANHMUC_KHO_NOIDEN_XUATKHO(string nOIXUATKHO)
        {
            var nOIXUATKHOParameter = nOIXUATKHO != null ?
                new ObjectParameter("NOIXUATKHO", nOIXUATKHO) :
                new ObjectParameter("NOIXUATKHO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DANHMUC_KHO_NOIDEN_XUATKHO_Result>("DANHMUC_KHO_NOIDEN_XUATKHO", nOIXUATKHOParameter);
        }
    
        public virtual ObjectResult<SP_LOAD_MAHINHTHUC_XUATKHO_Result> SP_LOAD_MAHINHTHUC_XUATKHO()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_LOAD_MAHINHTHUC_XUATKHO_Result>("SP_LOAD_MAHINHTHUC_XUATKHO");
        }
    
        public virtual ObjectResult<Load_MANVYC_XNKHO_SOI_Result> Load_MANVYC_XNKHO_SOI()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Load_MANVYC_XNKHO_SOI_Result>("Load_MANVYC_XNKHO_SOI");
        }
    
        public virtual ObjectResult<SP_LOAD_DMKHO_BY_IDMADV_gc___Result> SP_LOAD_DMKHO_BY_IDMADV_gc__(string iDMADV)
        {
            var iDMADVParameter = iDMADV != null ?
                new ObjectParameter("IDMADV", iDMADV) :
                new ObjectParameter("IDMADV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_LOAD_DMKHO_BY_IDMADV_gc___Result>("SP_LOAD_DMKHO_BY_IDMADV_gc__", iDMADVParameter);
        }
    
        public virtual int LOAD_DATA_MASOI_NHAPKHO_NKNB(string nOIDEN)
        {
            var nOIDENParameter = nOIDEN != null ?
                new ObjectParameter("NOIDEN", nOIDEN) :
                new ObjectParameter("NOIDEN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LOAD_DATA_MASOI_NHAPKHO_NKNB", nOIDENParameter);
        }
    
        public virtual ObjectResult<LOAD_DATA_MASOI_XUATKHO_THEO_XBAN_Result> LOAD_DATA_MASOI_XUATKHO_THEO_XBAN(string mAHTHUC, string mAKHO)
        {
            var mAHTHUCParameter = mAHTHUC != null ?
                new ObjectParameter("MAHTHUC", mAHTHUC) :
                new ObjectParameter("MAHTHUC", typeof(string));
    
            var mAKHOParameter = mAKHO != null ?
                new ObjectParameter("MAKHO", mAKHO) :
                new ObjectParameter("MAKHO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LOAD_DATA_MASOI_XUATKHO_THEO_XBAN_Result>("LOAD_DATA_MASOI_XUATKHO_THEO_XBAN", mAHTHUCParameter, mAKHOParameter);
        }
    
        public virtual ObjectResult<LOAD_DATA_MASOI_XUATKHO_THEO_XGC_Result> LOAD_DATA_MASOI_XUATKHO_THEO_XGC(string mAHTHUC, string mAKHO)
        {
            var mAHTHUCParameter = mAHTHUC != null ?
                new ObjectParameter("MAHTHUC", mAHTHUC) :
                new ObjectParameter("MAHTHUC", typeof(string));
    
            var mAKHOParameter = mAKHO != null ?
                new ObjectParameter("MAKHO", mAKHO) :
                new ObjectParameter("MAKHO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LOAD_DATA_MASOI_XUATKHO_THEO_XGC_Result>("LOAD_DATA_MASOI_XUATKHO_THEO_XGC", mAHTHUCParameter, mAKHOParameter);
        }
    
        public virtual ObjectResult<LOAD_DATA_MASOI_XUATKHO_THEO_XKNB_Result> LOAD_DATA_MASOI_XUATKHO_THEO_XKNB(string mAHTHUC, string mAKHO)
        {
            var mAHTHUCParameter = mAHTHUC != null ?
                new ObjectParameter("MAHTHUC", mAHTHUC) :
                new ObjectParameter("MAHTHUC", typeof(string));
    
            var mAKHOParameter = mAKHO != null ?
                new ObjectParameter("MAKHO", mAKHO) :
                new ObjectParameter("MAKHO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LOAD_DATA_MASOI_XUATKHO_THEO_XKNB_Result>("LOAD_DATA_MASOI_XUATKHO_THEO_XKNB", mAHTHUCParameter, mAKHOParameter);
        }
    
        public virtual ObjectResult<LOAD_DATA_MASOI_XUATKHO_THEO_XKNB_v2_Result> LOAD_DATA_MASOI_XUATKHO_THEO_XKNB_v2(string mAHTHUC, string mAKHO)
        {
            var mAHTHUCParameter = mAHTHUC != null ?
                new ObjectParameter("MAHTHUC", mAHTHUC) :
                new ObjectParameter("MAHTHUC", typeof(string));
    
            var mAKHOParameter = mAKHO != null ?
                new ObjectParameter("MAKHO", mAKHO) :
                new ObjectParameter("MAKHO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LOAD_DATA_MASOI_XUATKHO_THEO_XKNB_v2_Result>("LOAD_DATA_MASOI_XUATKHO_THEO_XKNB_v2", mAHTHUCParameter, mAKHOParameter);
        }
    
        public virtual ObjectResult<Sp_load_PhieuYCXuatkho_SOI_Result> Sp_load_PhieuYCXuatkho_SOI(string key)
        {
            var keyParameter = key != null ?
                new ObjectParameter("key", key) :
                new ObjectParameter("key", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_load_PhieuYCXuatkho_SOI_Result>("Sp_load_PhieuYCXuatkho_SOI", keyParameter);
        }
    
        public virtual ObjectResult<Sp_load_PhieuDaXuatkho_SOI_Result> Sp_load_PhieuDaXuatkho_SOI(string key)
        {
            var keyParameter = key != null ?
                new ObjectParameter("key", key) :
                new ObjectParameter("key", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_load_PhieuDaXuatkho_SOI_Result>("Sp_load_PhieuDaXuatkho_SOI", keyParameter);
        }
    
        public virtual ObjectResult<SP_LOAD_DATA_SOIGIACONG_CHUAHOIKHO_V2_Result> SP_LOAD_DATA_SOIGIACONG_CHUAHOIKHO_V2(string mAKHO, string mAVATTU)
        {
            var mAKHOParameter = mAKHO != null ?
                new ObjectParameter("MAKHO", mAKHO) :
                new ObjectParameter("MAKHO", typeof(string));
    
            var mAVATTUParameter = mAVATTU != null ?
                new ObjectParameter("MAVATTU", mAVATTU) :
                new ObjectParameter("MAVATTU", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_LOAD_DATA_SOIGIACONG_CHUAHOIKHO_V2_Result>("SP_LOAD_DATA_SOIGIACONG_CHUAHOIKHO_V2", mAKHOParameter, mAVATTUParameter);
        }
    
        public virtual ObjectResult<SP_COMBOBOX_LOAD_SOCTXN_CHATLUONG_Result> SP_COMBOBOX_LOAD_SOCTXN_CHATLUONG(string sOCTXN, string mANV)
        {
            var sOCTXNParameter = sOCTXN != null ?
                new ObjectParameter("SOCTXN", sOCTXN) :
                new ObjectParameter("SOCTXN", typeof(string));
    
            var mANVParameter = mANV != null ?
                new ObjectParameter("MANV", mANV) :
                new ObjectParameter("MANV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_COMBOBOX_LOAD_SOCTXN_CHATLUONG_Result>("SP_COMBOBOX_LOAD_SOCTXN_CHATLUONG", sOCTXNParameter, mANVParameter);
        }
    
        public virtual ObjectResult<SP_LOADCHITIET_KIEMTRACHATLUONG_DONVI_Result> SP_LOADCHITIET_KIEMTRACHATLUONG_DONVI(string sOCTXN)
        {
            var sOCTXNParameter = sOCTXN != null ?
                new ObjectParameter("SOCTXN", sOCTXN) :
                new ObjectParameter("SOCTXN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_LOADCHITIET_KIEMTRACHATLUONG_DONVI_Result>("SP_LOADCHITIET_KIEMTRACHATLUONG_DONVI", sOCTXNParameter);
        }
    
        public virtual int SP_KIEMTRACHATLUONG_UPDATE_DONVI(string sOCTXN, string mAVT, string hIEU, string lO, string mAPHIEUPD, string dONVIKIEMTRA, string mANVDONVI, string lOAI, string dANGLOI, string mANHACC)
        {
            var sOCTXNParameter = sOCTXN != null ?
                new ObjectParameter("SOCTXN", sOCTXN) :
                new ObjectParameter("SOCTXN", typeof(string));
    
            var mAVTParameter = mAVT != null ?
                new ObjectParameter("MAVT", mAVT) :
                new ObjectParameter("MAVT", typeof(string));
    
            var hIEUParameter = hIEU != null ?
                new ObjectParameter("HIEU", hIEU) :
                new ObjectParameter("HIEU", typeof(string));
    
            var lOParameter = lO != null ?
                new ObjectParameter("LO", lO) :
                new ObjectParameter("LO", typeof(string));
    
            var mAPHIEUPDParameter = mAPHIEUPD != null ?
                new ObjectParameter("MAPHIEUPD", mAPHIEUPD) :
                new ObjectParameter("MAPHIEUPD", typeof(string));
    
            var dONVIKIEMTRAParameter = dONVIKIEMTRA != null ?
                new ObjectParameter("DONVIKIEMTRA", dONVIKIEMTRA) :
                new ObjectParameter("DONVIKIEMTRA", typeof(string));
    
            var mANVDONVIParameter = mANVDONVI != null ?
                new ObjectParameter("MANVDONVI", mANVDONVI) :
                new ObjectParameter("MANVDONVI", typeof(string));
    
            var lOAIParameter = lOAI != null ?
                new ObjectParameter("LOAI", lOAI) :
                new ObjectParameter("LOAI", typeof(string));
    
            var dANGLOIParameter = dANGLOI != null ?
                new ObjectParameter("DANGLOI", dANGLOI) :
                new ObjectParameter("DANGLOI", typeof(string));
    
            var mANHACCParameter = mANHACC != null ?
                new ObjectParameter("MANHACC", mANHACC) :
                new ObjectParameter("MANHACC", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_KIEMTRACHATLUONG_UPDATE_DONVI", sOCTXNParameter, mAVTParameter, hIEUParameter, lOParameter, mAPHIEUPDParameter, dONVIKIEMTRAParameter, mANVDONVIParameter, lOAIParameter, dANGLOIParameter, mANHACCParameter);
        }
    
        public virtual int SP_KIEMTRACHATLUONG_FLAGXOA_UPDATE_FLAGXOA(string sOCTXN)
        {
            var sOCTXNParameter = sOCTXN != null ?
                new ObjectParameter("SOCTXN", sOCTXN) :
                new ObjectParameter("SOCTXN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_KIEMTRACHATLUONG_FLAGXOA_UPDATE_FLAGXOA", sOCTXNParameter);
        }
    
        public virtual ObjectResult<SP_RPT_INPHIEUKIEMTRACHATLUONG_SOI_Result> SP_RPT_INPHIEUKIEMTRACHATLUONG_SOI(string sOCTXN, string mANV)
        {
            var sOCTXNParameter = sOCTXN != null ?
                new ObjectParameter("SOCTXN", sOCTXN) :
                new ObjectParameter("SOCTXN", typeof(string));
    
            var mANVParameter = mANV != null ?
                new ObjectParameter("MANV", mANV) :
                new ObjectParameter("MANV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_RPT_INPHIEUKIEMTRACHATLUONG_SOI_Result>("SP_RPT_INPHIEUKIEMTRACHATLUONG_SOI", sOCTXNParameter, mANVParameter);
        }
    
        public virtual ObjectResult<SP_GC_DONHANGGCSOI_Result> SP_GC_DONHANGGCSOI()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GC_DONHANGGCSOI_Result>("SP_GC_DONHANGGCSOI");
        }
    
        public virtual ObjectResult<SP_GC_LOAD_DONVITH_Result> SP_GC_LOAD_DONVITH()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GC_LOAD_DONVITH_Result>("SP_GC_LOAD_DONVITH");
        }
    
        public virtual ObjectResult<SP_GC_LOAD_DONVIYC_ByMANV_Result> SP_GC_LOAD_DONVIYC_ByMANV(string manv)
        {
            var manvParameter = manv != null ?
                new ObjectParameter("manv", manv) :
                new ObjectParameter("manv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GC_LOAD_DONVIYC_ByMANV_Result>("SP_GC_LOAD_DONVIYC_ByMANV", manvParameter);
        }
    
        public virtual ObjectResult<SP_GC_LOAD_LOAIGIACONG_Result> SP_GC_LOAD_LOAIGIACONG()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GC_LOAD_LOAIGIACONG_Result>("SP_GC_LOAD_LOAIGIACONG");
        }
    
        public virtual ObjectResult<SP_GC_LOAD_MANVDONVITH_ByMADV_Result> SP_GC_LOAD_MANVDONVITH_ByMADV(string iDMaDV)
        {
            var iDMaDVParameter = iDMaDV != null ?
                new ObjectParameter("IDMaDV", iDMaDV) :
                new ObjectParameter("IDMaDV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GC_LOAD_MANVDONVITH_ByMADV_Result>("SP_GC_LOAD_MANVDONVITH_ByMADV", iDMaDVParameter);
        }
    
        public virtual ObjectResult<SP_GC_LOAD_MANVDONVIYC_ByMANV_Result> SP_GC_LOAD_MANVDONVIYC_ByMANV(string manv)
        {
            var manvParameter = manv != null ?
                new ObjectParameter("manv", manv) :
                new ObjectParameter("manv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GC_LOAD_MANVDONVIYC_ByMANV_Result>("SP_GC_LOAD_MANVDONVIYC_ByMANV", manvParameter);
        }
    
        public virtual int SP_GC_INSERT_DONHANGGCSOI(string mADH, string loaiGC, string iDDVYC, string iDDVTH, string mANV, Nullable<System.DateTime> ngaycn, string mANVDVYC, string mANVDVTH)
        {
            var mADHParameter = mADH != null ?
                new ObjectParameter("MADH", mADH) :
                new ObjectParameter("MADH", typeof(string));
    
            var loaiGCParameter = loaiGC != null ?
                new ObjectParameter("LoaiGC", loaiGC) :
                new ObjectParameter("LoaiGC", typeof(string));
    
            var iDDVYCParameter = iDDVYC != null ?
                new ObjectParameter("IDDVYC", iDDVYC) :
                new ObjectParameter("IDDVYC", typeof(string));
    
            var iDDVTHParameter = iDDVTH != null ?
                new ObjectParameter("IDDVTH", iDDVTH) :
                new ObjectParameter("IDDVTH", typeof(string));
    
            var mANVParameter = mANV != null ?
                new ObjectParameter("MANV", mANV) :
                new ObjectParameter("MANV", typeof(string));
    
            var ngaycnParameter = ngaycn.HasValue ?
                new ObjectParameter("Ngaycn", ngaycn) :
                new ObjectParameter("Ngaycn", typeof(System.DateTime));
    
            var mANVDVYCParameter = mANVDVYC != null ?
                new ObjectParameter("MANVDVYC", mANVDVYC) :
                new ObjectParameter("MANVDVYC", typeof(string));
    
            var mANVDVTHParameter = mANVDVTH != null ?
                new ObjectParameter("MANVDVTH", mANVDVTH) :
                new ObjectParameter("MANVDVTH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_GC_INSERT_DONHANGGCSOI", mADHParameter, loaiGCParameter, iDDVYCParameter, iDDVTHParameter, mANVParameter, ngaycnParameter, mANVDVYCParameter, mANVDVTHParameter);
        }
    
        public virtual ObjectResult<SP_GC_DMLoaiDonHang_Result> SP_GC_DMLoaiDonHang()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GC_DMLoaiDonHang_Result>("SP_GC_DMLoaiDonHang");
        }
    
        public virtual ObjectResult<SP_GC_MASOITHANHPHAM_Result> SP_GC_MASOITHANHPHAM()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GC_MASOITHANHPHAM_Result>("SP_GC_MASOITHANHPHAM");
        }
    
        public virtual ObjectResult<string> SP_GC_DONHANGGCSOI_TAODONHANG(string mANV, Nullable<System.DateTime> ngayCT)
        {
            var mANVParameter = mANV != null ?
                new ObjectParameter("MANV", mANV) :
                new ObjectParameter("MANV", typeof(string));
    
            var ngayCTParameter = ngayCT.HasValue ?
                new ObjectParameter("NgayCT", ngayCT) :
                new ObjectParameter("NgayCT", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_GC_DONHANGGCSOI_TAODONHANG", mANVParameter, ngayCTParameter);
        }
    
        public virtual int SP_GC_DELETE_DONHANGGCSOI(string madh)
        {
            var madhParameter = madh != null ?
                new ObjectParameter("Madh", madh) :
                new ObjectParameter("Madh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_GC_DELETE_DONHANGGCSOI", madhParameter);
        }
    
        public virtual int SP_GC_DELETE_DONHANGGCSOI_CT(string idkhoa)
        {
            var idkhoaParameter = idkhoa != null ?
                new ObjectParameter("idkhoa", idkhoa) :
                new ObjectParameter("idkhoa", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_GC_DELETE_DONHANGGCSOI_CT", idkhoaParameter);
        }
    
        public virtual ObjectResult<SP_GC_MADHGCSOI_DONHANGGCSOI_Result> SP_GC_MADHGCSOI_DONHANGGCSOI()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GC_MADHGCSOI_DONHANGGCSOI_Result>("SP_GC_MADHGCSOI_DONHANGGCSOI");
        }
    
        public virtual ObjectResult<SP_GC_LOAD_DONHANGGCSOI_CT_BYMADH_Result> SP_GC_LOAD_DONHANGGCSOI_CT_BYMADH(string madh)
        {
            var madhParameter = madh != null ?
                new ObjectParameter("madh", madh) :
                new ObjectParameter("madh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GC_LOAD_DONHANGGCSOI_CT_BYMADH_Result>("SP_GC_LOAD_DONHANGGCSOI_CT_BYMADH", madhParameter);
        }
    
        public virtual int SP_GC_UPDATE_DONHANGGCSOI_XX(string madh, Nullable<System.DateTime> ngayxx)
        {
            var madhParameter = madh != null ?
                new ObjectParameter("madh", madh) :
                new ObjectParameter("madh", typeof(string));
    
            var ngayxxParameter = ngayxx.HasValue ?
                new ObjectParameter("ngayxx", ngayxx) :
                new ObjectParameter("ngayxx", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_GC_UPDATE_DONHANGGCSOI_XX", madhParameter, ngayxxParameter);
        }
    
        public virtual ObjectResult<SP_GC_MADHGCSOI_DONHANGGCSOI_XNDVYC_Result> SP_GC_MADHGCSOI_DONHANGGCSOI_XNDVYC()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GC_MADHGCSOI_DONHANGGCSOI_XNDVYC_Result>("SP_GC_MADHGCSOI_DONHANGGCSOI_XNDVYC");
        }
    
        public virtual int SP_GC_UPDATE_DONHANGGCSOI_XN(string madh, Nullable<System.DateTime> ngayxx)
        {
            var madhParameter = madh != null ?
                new ObjectParameter("madh", madh) :
                new ObjectParameter("madh", typeof(string));
    
            var ngayxxParameter = ngayxx.HasValue ?
                new ObjectParameter("ngayxx", ngayxx) :
                new ObjectParameter("ngayxx", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_GC_UPDATE_DONHANGGCSOI_XN", madhParameter, ngayxxParameter);
        }
    
        public virtual ObjectResult<SP_GC_LOAD_GC_DMPHIEU_BANGKENHAPSOI_Result> SP_GC_LOAD_GC_DMPHIEU_BANGKENHAPSOI(string idmadv)
        {
            var idmadvParameter = idmadv != null ?
                new ObjectParameter("idmadv", idmadv) :
                new ObjectParameter("idmadv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GC_LOAD_GC_DMPHIEU_BANGKENHAPSOI_Result>("SP_GC_LOAD_GC_DMPHIEU_BANGKENHAPSOI", idmadvParameter);
        }
    
        public virtual ObjectResult<SP_LOAD_DMKHO_BY_IDMADV_Result> SP_LOAD_DMKHO_BY_IDMADV(string iDMADV)
        {
            var iDMADVParameter = iDMADV != null ?
                new ObjectParameter("IDMADV", iDMADV) :
                new ObjectParameter("IDMADV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_LOAD_DMKHO_BY_IDMADV_Result>("SP_LOAD_DMKHO_BY_IDMADV", iDMADVParameter);
        }
    
        public virtual ObjectResult<SP_BANGKENHAPSOI_MAHINHTHUC_LOAD_MAHTHUC_MADV_Result> SP_BANGKENHAPSOI_MAHINHTHUC_LOAD_MAHTHUC_MADV(string mADV)
        {
            var mADVParameter = mADV != null ?
                new ObjectParameter("MADV", mADV) :
                new ObjectParameter("MADV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_BANGKENHAPSOI_MAHINHTHUC_LOAD_MAHTHUC_MADV_Result>("SP_BANGKENHAPSOI_MAHINHTHUC_LOAD_MAHTHUC_MADV", mADVParameter);
        }
    
        public virtual ObjectResult<SP_LDD_DMNOIDEN_LOAD_BY_MADV_MANV_Result> SP_LDD_DMNOIDEN_LOAD_BY_MADV_MANV(string mADV, string mANV)
        {
            var mADVParameter = mADV != null ?
                new ObjectParameter("MADV", mADV) :
                new ObjectParameter("MADV", typeof(string));
    
            var mANVParameter = mANV != null ?
                new ObjectParameter("MANV", mANV) :
                new ObjectParameter("MANV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_LDD_DMNOIDEN_LOAD_BY_MADV_MANV_Result>("SP_LDD_DMNOIDEN_LOAD_BY_MADV_MANV", mADVParameter, mANVParameter);
        }
    
        public virtual ObjectResult<SP_GC_MACONGTHUC_LOAD_NVXX_BY_MADV_Result> SP_GC_MACONGTHUC_LOAD_NVXX_BY_MADV(string mADV)
        {
            var mADVParameter = mADV != null ?
                new ObjectParameter("MADV", mADV) :
                new ObjectParameter("MADV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GC_MACONGTHUC_LOAD_NVXX_BY_MADV_Result>("SP_GC_MACONGTHUC_LOAD_NVXX_BY_MADV", mADVParameter);
        }
    
        public virtual ObjectResult<string> SP_GC_TAOPHIEUBANGKE_GC_DMPHIEU_BANGKENHAPSOI(Nullable<System.DateTime> ngay, string mADV)
        {
            var ngayParameter = ngay.HasValue ?
                new ObjectParameter("ngay", ngay) :
                new ObjectParameter("ngay", typeof(System.DateTime));
    
            var mADVParameter = mADV != null ?
                new ObjectParameter("MADV", mADV) :
                new ObjectParameter("MADV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_GC_TAOPHIEUBANGKE_GC_DMPHIEU_BANGKENHAPSOI", ngayParameter, mADVParameter);
        }
    
        public virtual ObjectResult<SP_CTPHIEUXUATGC_LOAD_MACONGTHUC_BY_MADV_MAKH_Result> SP_CTPHIEUXUATGC_LOAD_MACONGTHUC_BY_MADV_MAKH(string kEY, string mADV, string sOPHIEU)
        {
            var kEYParameter = kEY != null ?
                new ObjectParameter("KEY", kEY) :
                new ObjectParameter("KEY", typeof(string));
    
            var mADVParameter = mADV != null ?
                new ObjectParameter("MADV", mADV) :
                new ObjectParameter("MADV", typeof(string));
    
            var sOPHIEUParameter = sOPHIEU != null ?
                new ObjectParameter("SOPHIEU", sOPHIEU) :
                new ObjectParameter("SOPHIEU", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_CTPHIEUXUATGC_LOAD_MACONGTHUC_BY_MADV_MAKH_Result>("SP_CTPHIEUXUATGC_LOAD_MACONGTHUC_BY_MADV_MAKH", kEYParameter, mADVParameter, sOPHIEUParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> SP_GC_CHITIETCONGTHUC_LOAD_SLPD_BY_KHOA(string kHOA)
        {
            var kHOAParameter = kHOA != null ?
                new ObjectParameter("KHOA", kHOA) :
                new ObjectParameter("KHOA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("SP_GC_CHITIETCONGTHUC_LOAD_SLPD_BY_KHOA", kHOAParameter);
        }
    
        public virtual ObjectResult<SP_GC_CHITIETCONGTHUC_LOAD_SLPD_BY_KHOA_211223_Result> SP_GC_CHITIETCONGTHUC_LOAD_SLPD_BY_KHOA_211223(string kHOA)
        {
            var kHOAParameter = kHOA != null ?
                new ObjectParameter("KHOA", kHOA) :
                new ObjectParameter("KHOA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GC_CHITIETCONGTHUC_LOAD_SLPD_BY_KHOA_211223_Result>("SP_GC_CHITIETCONGTHUC_LOAD_SLPD_BY_KHOA_211223", kHOAParameter);
        }
    
        public virtual ObjectResult<SP_GC_DMNGUYENLIEU_LOAD_COMBOBOX_Result> SP_GC_DMNGUYENLIEU_LOAD_COMBOBOX(string kEY)
        {
            var kEYParameter = kEY != null ?
                new ObjectParameter("KEY", kEY) :
                new ObjectParameter("KEY", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GC_DMNGUYENLIEU_LOAD_COMBOBOX_Result>("SP_GC_DMNGUYENLIEU_LOAD_COMBOBOX", kEYParameter);
        }
    
        public virtual ObjectResult<SP_GC_DMDANGCONGDOAN_LOAD_COMBOBOX_Result> SP_GC_DMDANGCONGDOAN_LOAD_COMBOBOX(string kEY)
        {
            var kEYParameter = kEY != null ?
                new ObjectParameter("KEY", kEY) :
                new ObjectParameter("KEY", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GC_DMDANGCONGDOAN_LOAD_COMBOBOX_Result>("SP_GC_DMDANGCONGDOAN_LOAD_COMBOBOX", kEYParameter);
        }
    
        public virtual ObjectResult<SP_GC_LOAD_MADH_GCSOI_Result> SP_GC_LOAD_MADH_GCSOI()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GC_LOAD_MADH_GCSOI_Result>("SP_GC_LOAD_MADH_GCSOI");
        }
    
        public virtual ObjectResult<SP_GC_DONVITINH_LOAD_Result> SP_GC_DONVITINH_LOAD()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GC_DONVITINH_LOAD_Result>("SP_GC_DONVITINH_LOAD");
        }
    
        public virtual ObjectResult<SP_GC_DMMACONGDOAN_LOAD_COMBOBOX_Result> SP_GC_DMMACONGDOAN_LOAD_COMBOBOX(string kEY)
        {
            var kEYParameter = kEY != null ?
                new ObjectParameter("KEY", kEY) :
                new ObjectParameter("KEY", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GC_DMMACONGDOAN_LOAD_COMBOBOX_Result>("SP_GC_DMMACONGDOAN_LOAD_COMBOBOX", kEYParameter);
        }
    
        public virtual ObjectResult<SP_GC_LOAD_MASOITHANHPHAM_BY_MADHGCSOI_Result> SP_GC_LOAD_MASOITHANHPHAM_BY_MADHGCSOI(string madh)
        {
            var madhParameter = madh != null ?
                new ObjectParameter("madh", madh) :
                new ObjectParameter("madh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GC_LOAD_MASOITHANHPHAM_BY_MADHGCSOI_Result>("SP_GC_LOAD_MASOITHANHPHAM_BY_MADHGCSOI", madhParameter);
        }
    
        public virtual int SP_GC_CTPHIEUXUATGIACONG_INSERT_130415(string kHOACTHUC, string sOCTXN, string mASOI, string mASOICHAP, string hIEU, string lO, Nullable<decimal> sOLUONGNHAP, Nullable<decimal> sOLUONGXUAT, Nullable<decimal> sLHAOHUTDM, string dVT, Nullable<int> sOTRUC, Nullable<decimal> sOCANH, Nullable<decimal> kHOTRUC, Nullable<decimal> cHIEUDAI, string gHICHU, string sOPHIEU, string mACONGDOAN, string dANGCONGDOAN)
        {
            var kHOACTHUCParameter = kHOACTHUC != null ?
                new ObjectParameter("KHOACTHUC", kHOACTHUC) :
                new ObjectParameter("KHOACTHUC", typeof(string));
    
            var sOCTXNParameter = sOCTXN != null ?
                new ObjectParameter("SOCTXN", sOCTXN) :
                new ObjectParameter("SOCTXN", typeof(string));
    
            var mASOIParameter = mASOI != null ?
                new ObjectParameter("MASOI", mASOI) :
                new ObjectParameter("MASOI", typeof(string));
    
            var mASOICHAPParameter = mASOICHAP != null ?
                new ObjectParameter("MASOICHAP", mASOICHAP) :
                new ObjectParameter("MASOICHAP", typeof(string));
    
            var hIEUParameter = hIEU != null ?
                new ObjectParameter("HIEU", hIEU) :
                new ObjectParameter("HIEU", typeof(string));
    
            var lOParameter = lO != null ?
                new ObjectParameter("LO", lO) :
                new ObjectParameter("LO", typeof(string));
    
            var sOLUONGNHAPParameter = sOLUONGNHAP.HasValue ?
                new ObjectParameter("SOLUONGNHAP", sOLUONGNHAP) :
                new ObjectParameter("SOLUONGNHAP", typeof(decimal));
    
            var sOLUONGXUATParameter = sOLUONGXUAT.HasValue ?
                new ObjectParameter("SOLUONGXUAT", sOLUONGXUAT) :
                new ObjectParameter("SOLUONGXUAT", typeof(decimal));
    
            var sLHAOHUTDMParameter = sLHAOHUTDM.HasValue ?
                new ObjectParameter("SLHAOHUTDM", sLHAOHUTDM) :
                new ObjectParameter("SLHAOHUTDM", typeof(decimal));
    
            var dVTParameter = dVT != null ?
                new ObjectParameter("DVT", dVT) :
                new ObjectParameter("DVT", typeof(string));
    
            var sOTRUCParameter = sOTRUC.HasValue ?
                new ObjectParameter("SOTRUC", sOTRUC) :
                new ObjectParameter("SOTRUC", typeof(int));
    
            var sOCANHParameter = sOCANH.HasValue ?
                new ObjectParameter("SOCANH", sOCANH) :
                new ObjectParameter("SOCANH", typeof(decimal));
    
            var kHOTRUCParameter = kHOTRUC.HasValue ?
                new ObjectParameter("KHOTRUC", kHOTRUC) :
                new ObjectParameter("KHOTRUC", typeof(decimal));
    
            var cHIEUDAIParameter = cHIEUDAI.HasValue ?
                new ObjectParameter("CHIEUDAI", cHIEUDAI) :
                new ObjectParameter("CHIEUDAI", typeof(decimal));
    
            var gHICHUParameter = gHICHU != null ?
                new ObjectParameter("GHICHU", gHICHU) :
                new ObjectParameter("GHICHU", typeof(string));
    
            var sOPHIEUParameter = sOPHIEU != null ?
                new ObjectParameter("SOPHIEU", sOPHIEU) :
                new ObjectParameter("SOPHIEU", typeof(string));
    
            var mACONGDOANParameter = mACONGDOAN != null ?
                new ObjectParameter("MACONGDOAN", mACONGDOAN) :
                new ObjectParameter("MACONGDOAN", typeof(string));
    
            var dANGCONGDOANParameter = dANGCONGDOAN != null ?
                new ObjectParameter("DANGCONGDOAN", dANGCONGDOAN) :
                new ObjectParameter("DANGCONGDOAN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_GC_CTPHIEUXUATGIACONG_INSERT_130415", kHOACTHUCParameter, sOCTXNParameter, mASOIParameter, mASOICHAPParameter, hIEUParameter, lOParameter, sOLUONGNHAPParameter, sOLUONGXUATParameter, sLHAOHUTDMParameter, dVTParameter, sOTRUCParameter, sOCANHParameter, kHOTRUCParameter, cHIEUDAIParameter, gHICHUParameter, sOPHIEUParameter, mACONGDOANParameter, dANGCONGDOANParameter);
        }
    
        public virtual int SP_GC_CTPHIEUXUATGIACONG_INSERT_22122023(string kHOACTHUC, string sOCTXN, string mASOI, string mASOICHAP, string hIEU, string lO, Nullable<decimal> sOLUONGNHAP, Nullable<decimal> sOLUONGXUAT, Nullable<decimal> sLHAOHUTDM, string dVT, Nullable<int> sOTRUC, Nullable<decimal> sOCANH, Nullable<decimal> kHOTRUC, Nullable<decimal> cHIEUDAI, string gHICHU, string sOPHIEU, string mACONGDOAN, string dANGCONGDOAN, string mADH_GCSOI, string mASOIHOANTAT)
        {
            var kHOACTHUCParameter = kHOACTHUC != null ?
                new ObjectParameter("KHOACTHUC", kHOACTHUC) :
                new ObjectParameter("KHOACTHUC", typeof(string));
    
            var sOCTXNParameter = sOCTXN != null ?
                new ObjectParameter("SOCTXN", sOCTXN) :
                new ObjectParameter("SOCTXN", typeof(string));
    
            var mASOIParameter = mASOI != null ?
                new ObjectParameter("MASOI", mASOI) :
                new ObjectParameter("MASOI", typeof(string));
    
            var mASOICHAPParameter = mASOICHAP != null ?
                new ObjectParameter("MASOICHAP", mASOICHAP) :
                new ObjectParameter("MASOICHAP", typeof(string));
    
            var hIEUParameter = hIEU != null ?
                new ObjectParameter("HIEU", hIEU) :
                new ObjectParameter("HIEU", typeof(string));
    
            var lOParameter = lO != null ?
                new ObjectParameter("LO", lO) :
                new ObjectParameter("LO", typeof(string));
    
            var sOLUONGNHAPParameter = sOLUONGNHAP.HasValue ?
                new ObjectParameter("SOLUONGNHAP", sOLUONGNHAP) :
                new ObjectParameter("SOLUONGNHAP", typeof(decimal));
    
            var sOLUONGXUATParameter = sOLUONGXUAT.HasValue ?
                new ObjectParameter("SOLUONGXUAT", sOLUONGXUAT) :
                new ObjectParameter("SOLUONGXUAT", typeof(decimal));
    
            var sLHAOHUTDMParameter = sLHAOHUTDM.HasValue ?
                new ObjectParameter("SLHAOHUTDM", sLHAOHUTDM) :
                new ObjectParameter("SLHAOHUTDM", typeof(decimal));
    
            var dVTParameter = dVT != null ?
                new ObjectParameter("DVT", dVT) :
                new ObjectParameter("DVT", typeof(string));
    
            var sOTRUCParameter = sOTRUC.HasValue ?
                new ObjectParameter("SOTRUC", sOTRUC) :
                new ObjectParameter("SOTRUC", typeof(int));
    
            var sOCANHParameter = sOCANH.HasValue ?
                new ObjectParameter("SOCANH", sOCANH) :
                new ObjectParameter("SOCANH", typeof(decimal));
    
            var kHOTRUCParameter = kHOTRUC.HasValue ?
                new ObjectParameter("KHOTRUC", kHOTRUC) :
                new ObjectParameter("KHOTRUC", typeof(decimal));
    
            var cHIEUDAIParameter = cHIEUDAI.HasValue ?
                new ObjectParameter("CHIEUDAI", cHIEUDAI) :
                new ObjectParameter("CHIEUDAI", typeof(decimal));
    
            var gHICHUParameter = gHICHU != null ?
                new ObjectParameter("GHICHU", gHICHU) :
                new ObjectParameter("GHICHU", typeof(string));
    
            var sOPHIEUParameter = sOPHIEU != null ?
                new ObjectParameter("SOPHIEU", sOPHIEU) :
                new ObjectParameter("SOPHIEU", typeof(string));
    
            var mACONGDOANParameter = mACONGDOAN != null ?
                new ObjectParameter("MACONGDOAN", mACONGDOAN) :
                new ObjectParameter("MACONGDOAN", typeof(string));
    
            var dANGCONGDOANParameter = dANGCONGDOAN != null ?
                new ObjectParameter("DANGCONGDOAN", dANGCONGDOAN) :
                new ObjectParameter("DANGCONGDOAN", typeof(string));
    
            var mADH_GCSOIParameter = mADH_GCSOI != null ?
                new ObjectParameter("MADH_GCSOI", mADH_GCSOI) :
                new ObjectParameter("MADH_GCSOI", typeof(string));
    
            var mASOIHOANTATParameter = mASOIHOANTAT != null ?
                new ObjectParameter("MASOIHOANTAT", mASOIHOANTAT) :
                new ObjectParameter("MASOIHOANTAT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_GC_CTPHIEUXUATGIACONG_INSERT_22122023", kHOACTHUCParameter, sOCTXNParameter, mASOIParameter, mASOICHAPParameter, hIEUParameter, lOParameter, sOLUONGNHAPParameter, sOLUONGXUATParameter, sLHAOHUTDMParameter, dVTParameter, sOTRUCParameter, sOCANHParameter, kHOTRUCParameter, cHIEUDAIParameter, gHICHUParameter, sOPHIEUParameter, mACONGDOANParameter, dANGCONGDOANParameter, mADH_GCSOIParameter, mASOIHOANTATParameter);
        }
    
        public virtual int SP_GC_CTPHIEUXUATGIACONG_BK_DELETE(string sOPHIEU)
        {
            var sOPHIEUParameter = sOPHIEU != null ?
                new ObjectParameter("SOPHIEU", sOPHIEU) :
                new ObjectParameter("SOPHIEU", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_GC_CTPHIEUXUATGIACONG_BK_DELETE", sOPHIEUParameter);
        }
    
        public virtual int SP_GC_DELETE_CTPHIEUXUATGIACONG_BYKHOA(string iDKHOA)
        {
            var iDKHOAParameter = iDKHOA != null ?
                new ObjectParameter("IDKHOA", iDKHOA) :
                new ObjectParameter("IDKHOA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_GC_DELETE_CTPHIEUXUATGIACONG_BYKHOA", iDKHOAParameter);
        }
    
        public virtual int SP_GC_UPDATE_DONHANGGCSOI_BOXN(string madh, Nullable<System.DateTime> ngayxx)
        {
            var madhParameter = madh != null ?
                new ObjectParameter("madh", madh) :
                new ObjectParameter("madh", typeof(string));
    
            var ngayxxParameter = ngayxx.HasValue ?
                new ObjectParameter("ngayxx", ngayxx) :
                new ObjectParameter("ngayxx", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_GC_UPDATE_DONHANGGCSOI_BOXN", madhParameter, ngayxxParameter);
        }
    
        public virtual ObjectResult<SP_LOAD_MADINHMUC_TUBANGKEGCSOI_Result> SP_LOAD_MADINHMUC_TUBANGKEGCSOI(string mAVT)
        {
            var mAVTParameter = mAVT != null ?
                new ObjectParameter("MAVT", mAVT) :
                new ObjectParameter("MAVT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_LOAD_MADINHMUC_TUBANGKEGCSOI_Result>("SP_LOAD_MADINHMUC_TUBANGKEGCSOI", mAVTParameter);
        }
    
        public virtual ObjectResult<SP_GC_GC_DMPHIEU_BANGKENHAPSOI_BY_MADV_HLXX_Result> SP_GC_GC_DMPHIEU_BANGKENHAPSOI_BY_MADV_HLXX(string mADV)
        {
            var mADVParameter = mADV != null ?
                new ObjectParameter("MADV", mADV) :
                new ObjectParameter("MADV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GC_GC_DMPHIEU_BANGKENHAPSOI_BY_MADV_HLXX_Result>("SP_GC_GC_DMPHIEU_BANGKENHAPSOI_BY_MADV_HLXX", mADVParameter);
        }
    
        public virtual ObjectResult<SP_GC_GC_DMPHIEU_BANGKENHAPSOI_BY_MADV_Result> SP_GC_GC_DMPHIEU_BANGKENHAPSOI_BY_MADV(string mADV, string maLoaiCongDoan)
        {
            var mADVParameter = mADV != null ?
                new ObjectParameter("MADV", mADV) :
                new ObjectParameter("MADV", typeof(string));
    
            var maLoaiCongDoanParameter = maLoaiCongDoan != null ?
                new ObjectParameter("MaLoaiCongDoan", maLoaiCongDoan) :
                new ObjectParameter("MaLoaiCongDoan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GC_GC_DMPHIEU_BANGKENHAPSOI_BY_MADV_Result>("SP_GC_GC_DMPHIEU_BANGKENHAPSOI_BY_MADV", mADVParameter, maLoaiCongDoanParameter);
        }
    
        public virtual ObjectResult<SP_GC_BANGKENHAPSOI_XEMXET_LOAD_MANVKETOAN_BY_MAHINHTHUC_Result> SP_GC_BANGKENHAPSOI_XEMXET_LOAD_MANVKETOAN_BY_MAHINHTHUC(string mAHINHTHUC, string mADV)
        {
            var mAHINHTHUCParameter = mAHINHTHUC != null ?
                new ObjectParameter("MAHINHTHUC", mAHINHTHUC) :
                new ObjectParameter("MAHINHTHUC", typeof(string));
    
            var mADVParameter = mADV != null ?
                new ObjectParameter("MADV", mADV) :
                new ObjectParameter("MADV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GC_BANGKENHAPSOI_XEMXET_LOAD_MANVKETOAN_BY_MAHINHTHUC_Result>("SP_GC_BANGKENHAPSOI_XEMXET_LOAD_MANVKETOAN_BY_MAHINHTHUC", mAHINHTHUCParameter, mADVParameter);
        }
    
        public virtual int SP_GC_GC_DMPHIEU_BANGKENHAPSOI_DVXX_BySOPHIEU(Nullable<System.DateTime> ngayXX, string soPhieu, string manv_KT)
        {
            var ngayXXParameter = ngayXX.HasValue ?
                new ObjectParameter("NgayXX", ngayXX) :
                new ObjectParameter("NgayXX", typeof(System.DateTime));
    
            var soPhieuParameter = soPhieu != null ?
                new ObjectParameter("SoPhieu", soPhieu) :
                new ObjectParameter("SoPhieu", typeof(string));
    
            var manv_KTParameter = manv_KT != null ?
                new ObjectParameter("Manv_KT", manv_KT) :
                new ObjectParameter("Manv_KT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_GC_GC_DMPHIEU_BANGKENHAPSOI_DVXX_BySOPHIEU", ngayXXParameter, soPhieuParameter, manv_KTParameter);
        }
    
        public virtual int SP_GC_UPDATE_BOXX_DMPHIEU_BANGKENHAPSOI(string sophieu, Nullable<System.DateTime> ngay)
        {
            var sophieuParameter = sophieu != null ?
                new ObjectParameter("Sophieu", sophieu) :
                new ObjectParameter("Sophieu", typeof(string));
    
            var ngayParameter = ngay.HasValue ?
                new ObjectParameter("ngay", ngay) :
                new ObjectParameter("ngay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_GC_UPDATE_BOXX_DMPHIEU_BANGKENHAPSOI", sophieuParameter, ngayParameter);
        }
    
        public virtual int Sp_KethuaQuyenUser_KhoVT_Soi2023(string mANV, string mANVKthua)
        {
            var mANVParameter = mANV != null ?
                new ObjectParameter("MANV", mANV) :
                new ObjectParameter("MANV", typeof(string));
    
            var mANVKthuaParameter = mANVKthua != null ?
                new ObjectParameter("MANVKthua", mANVKthua) :
                new ObjectParameter("MANVKthua", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_KethuaQuyenUser_KhoVT_Soi2023", mANVParameter, mANVKthuaParameter);
        }
    
        public virtual int INSERT_INVOICE_NL_DMPHIEU(string mAPHIEUPD, string sOHOPDONG, string mavt, string iNVOICE, string tOKHAI, Nullable<decimal> gIANHAP, string qUOCGIA, Nullable<System.DateTime> nGAYNHAPHANG, string mASPKHACH, string mAKH, string mANVCAPNHAT, Nullable<System.DateTime> nGAYCAPNHAT, Nullable<System.Guid> khoa_id)
        {
            var mAPHIEUPDParameter = mAPHIEUPD != null ?
                new ObjectParameter("MAPHIEUPD", mAPHIEUPD) :
                new ObjectParameter("MAPHIEUPD", typeof(string));
    
            var sOHOPDONGParameter = sOHOPDONG != null ?
                new ObjectParameter("SOHOPDONG", sOHOPDONG) :
                new ObjectParameter("SOHOPDONG", typeof(string));
    
            var mavtParameter = mavt != null ?
                new ObjectParameter("Mavt", mavt) :
                new ObjectParameter("Mavt", typeof(string));
    
            var iNVOICEParameter = iNVOICE != null ?
                new ObjectParameter("INVOICE", iNVOICE) :
                new ObjectParameter("INVOICE", typeof(string));
    
            var tOKHAIParameter = tOKHAI != null ?
                new ObjectParameter("TOKHAI", tOKHAI) :
                new ObjectParameter("TOKHAI", typeof(string));
    
            var gIANHAPParameter = gIANHAP.HasValue ?
                new ObjectParameter("GIANHAP", gIANHAP) :
                new ObjectParameter("GIANHAP", typeof(decimal));
    
            var qUOCGIAParameter = qUOCGIA != null ?
                new ObjectParameter("QUOCGIA", qUOCGIA) :
                new ObjectParameter("QUOCGIA", typeof(string));
    
            var nGAYNHAPHANGParameter = nGAYNHAPHANG.HasValue ?
                new ObjectParameter("NGAYNHAPHANG", nGAYNHAPHANG) :
                new ObjectParameter("NGAYNHAPHANG", typeof(System.DateTime));
    
            var mASPKHACHParameter = mASPKHACH != null ?
                new ObjectParameter("MASPKHACH", mASPKHACH) :
                new ObjectParameter("MASPKHACH", typeof(string));
    
            var mAKHParameter = mAKH != null ?
                new ObjectParameter("MAKH", mAKH) :
                new ObjectParameter("MAKH", typeof(string));
    
            var mANVCAPNHATParameter = mANVCAPNHAT != null ?
                new ObjectParameter("MANVCAPNHAT", mANVCAPNHAT) :
                new ObjectParameter("MANVCAPNHAT", typeof(string));
    
            var nGAYCAPNHATParameter = nGAYCAPNHAT.HasValue ?
                new ObjectParameter("NGAYCAPNHAT", nGAYCAPNHAT) :
                new ObjectParameter("NGAYCAPNHAT", typeof(System.DateTime));
    
            var khoa_idParameter = khoa_id.HasValue ?
                new ObjectParameter("Khoa_id", khoa_id) :
                new ObjectParameter("Khoa_id", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERT_INVOICE_NL_DMPHIEU", mAPHIEUPDParameter, sOHOPDONGParameter, mavtParameter, iNVOICEParameter, tOKHAIParameter, gIANHAPParameter, qUOCGIAParameter, nGAYNHAPHANGParameter, mASPKHACHParameter, mAKHParameter, mANVCAPNHATParameter, nGAYCAPNHATParameter, khoa_idParameter);
        }
    
        public virtual int SOI2024_LOAD_DATA_MASOI_NHAPKHO_NKNB_BYSOCTXN(string nOIDEN, string mAHTHUC)
        {
            var nOIDENParameter = nOIDEN != null ?
                new ObjectParameter("NOIDEN", nOIDEN) :
                new ObjectParameter("NOIDEN", typeof(string));
    
            var mAHTHUCParameter = mAHTHUC != null ?
                new ObjectParameter("MAHTHUC", mAHTHUC) :
                new ObjectParameter("MAHTHUC", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SOI2024_LOAD_DATA_MASOI_NHAPKHO_NKNB_BYSOCTXN", nOIDENParameter, mAHTHUCParameter);
        }
    
        public virtual int SOI2024_LOAD_DATA_MASOI_NHAPKHO_NKNB_XBAN_XGC_v1(string nOIDEN, string mAHTHUC)
        {
            var nOIDENParameter = nOIDEN != null ?
                new ObjectParameter("NOIDEN", nOIDEN) :
                new ObjectParameter("NOIDEN", typeof(string));
    
            var mAHTHUCParameter = mAHTHUC != null ?
                new ObjectParameter("MAHTHUC", mAHTHUC) :
                new ObjectParameter("MAHTHUC", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SOI2024_LOAD_DATA_MASOI_NHAPKHO_NKNB_XBAN_XGC_v1", nOIDENParameter, mAHTHUCParameter);
        }
    
        public virtual ObjectResult<SP_NL_Load_NL_DMNHOMNGLIEU_Result> SP_NL_Load_NL_DMNHOMNGLIEU()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_NL_Load_NL_DMNHOMNGLIEU_Result>("SP_NL_Load_NL_DMNHOMNGLIEU");
        }
    
        public virtual ObjectResult<sp_Nl_TaoMaVT_Result> sp_Nl_TaoMaVT(string nhomsoi, string cs1, string cs2)
        {
            var nhomsoiParameter = nhomsoi != null ?
                new ObjectParameter("nhomsoi", nhomsoi) :
                new ObjectParameter("nhomsoi", typeof(string));
    
            var cs1Parameter = cs1 != null ?
                new ObjectParameter("cs1", cs1) :
                new ObjectParameter("cs1", typeof(string));
    
            var cs2Parameter = cs2 != null ?
                new ObjectParameter("cs2", cs2) :
                new ObjectParameter("cs2", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Nl_TaoMaVT_Result>("sp_Nl_TaoMaVT", nhomsoiParameter, cs1Parameter, cs2Parameter);
        }
    
        public virtual ObjectResult<VATTU2024_SP_LOAD_DATA_SOIGIACONG_CHUAHOIKHO_Result> VATTU2024_SP_LOAD_DATA_SOIGIACONG_CHUAHOIKHO(string mAKHO, string mAVATTU)
        {
            var mAKHOParameter = mAKHO != null ?
                new ObjectParameter("MAKHO", mAKHO) :
                new ObjectParameter("MAKHO", typeof(string));
    
            var mAVATTUParameter = mAVATTU != null ?
                new ObjectParameter("MAVATTU", mAVATTU) :
                new ObjectParameter("MAVATTU", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VATTU2024_SP_LOAD_DATA_SOIGIACONG_CHUAHOIKHO_Result>("VATTU2024_SP_LOAD_DATA_SOIGIACONG_CHUAHOIKHO", mAKHOParameter, mAVATTUParameter);
        }
    
        public virtual ObjectResult<VATTU2024_SP_LOAD_SOPHIEU_SOIGIACONG_CHUAHOIKHO_Result> VATTU2024_SP_LOAD_SOPHIEU_SOIGIACONG_CHUAHOIKHO(string mAKHO, string mAVATTU)
        {
            var mAKHOParameter = mAKHO != null ?
                new ObjectParameter("MAKHO", mAKHO) :
                new ObjectParameter("MAKHO", typeof(string));
    
            var mAVATTUParameter = mAVATTU != null ?
                new ObjectParameter("MAVATTU", mAVATTU) :
                new ObjectParameter("MAVATTU", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VATTU2024_SP_LOAD_SOPHIEU_SOIGIACONG_CHUAHOIKHO_Result>("VATTU2024_SP_LOAD_SOPHIEU_SOIGIACONG_CHUAHOIKHO", mAKHOParameter, mAVATTUParameter);
        }
    
        public virtual ObjectResult<SP_GETLIST_NL_DMPHIEU_Result> SP_GETLIST_NL_DMPHIEU()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GETLIST_NL_DMPHIEU_Result>("SP_GETLIST_NL_DMPHIEU");
        }
    
        public virtual ObjectResult<VATTU2024_SPLOAD_DONHANGGCSOI_PHIEUYCXUATKHO_Result> VATTU2024_SPLOAD_DONHANGGCSOI_PHIEUYCXUATKHO()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VATTU2024_SPLOAD_DONHANGGCSOI_PHIEUYCXUATKHO_Result>("VATTU2024_SPLOAD_DONHANGGCSOI_PHIEUYCXUATKHO");
        }
    
        public virtual ObjectResult<VATTU2024_SP_GC_DMNGUYENLIEU_SOIHOANTAT_Result> VATTU2024_SP_GC_DMNGUYENLIEU_SOIHOANTAT(string kEY)
        {
            var kEYParameter = kEY != null ?
                new ObjectParameter("KEY", kEY) :
                new ObjectParameter("KEY", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VATTU2024_SP_GC_DMNGUYENLIEU_SOIHOANTAT_Result>("VATTU2024_SP_GC_DMNGUYENLIEU_SOIHOANTAT", kEYParameter);
        }
    
        public virtual ObjectResult<VATTU2024_SPLOAD_MADONHANG_ND_XK_Result> VATTU2024_SPLOAD_MADONHANG_ND_XK(string mADH)
        {
            var mADHParameter = mADH != null ?
                new ObjectParameter("MADH", mADH) :
                new ObjectParameter("MADH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VATTU2024_SPLOAD_MADONHANG_ND_XK_Result>("VATTU2024_SPLOAD_MADONHANG_ND_XK", mADHParameter);
        }
    
        public virtual ObjectResult<DINHMUC_SOIGC_Result> DINHMUC_SOIGC(string mASOIHOANTAT, string sophieu)
        {
            var mASOIHOANTATParameter = mASOIHOANTAT != null ?
                new ObjectParameter("MASOIHOANTAT", mASOIHOANTAT) :
                new ObjectParameter("MASOIHOANTAT", typeof(string));
    
            var sophieuParameter = sophieu != null ?
                new ObjectParameter("sophieu", sophieu) :
                new ObjectParameter("sophieu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DINHMUC_SOIGC_Result>("DINHMUC_SOIGC", mASOIHOANTATParameter, sophieuParameter);
        }
    
        public virtual ObjectResult<VATTU2024_SPLOAD_GC_CTPHIEUXUATGC_Result> VATTU2024_SPLOAD_GC_CTPHIEUXUATGC(string sOPHIEU, string kEY)
        {
            var sOPHIEUParameter = sOPHIEU != null ?
                new ObjectParameter("SOPHIEU", sOPHIEU) :
                new ObjectParameter("SOPHIEU", typeof(string));
    
            var kEYParameter = kEY != null ?
                new ObjectParameter("KEY", kEY) :
                new ObjectParameter("KEY", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VATTU2024_SPLOAD_GC_CTPHIEUXUATGC_Result>("VATTU2024_SPLOAD_GC_CTPHIEUXUATGC", sOPHIEUParameter, kEYParameter);
        }
    
        public virtual int SP_DMPHIEU_BANGKENHAPSOI_INSERT_211223(string sOPHIEU, string mADV, Nullable<int> nAM, Nullable<int> tHANG, string mAKH, string nHAPKHO, string lYDOSANXUAT, string mALOAICONGDOAN, string cONGDOAN, string mANV, string mANV_XX, string loaiYCSX)
        {
            var sOPHIEUParameter = sOPHIEU != null ?
                new ObjectParameter("SOPHIEU", sOPHIEU) :
                new ObjectParameter("SOPHIEU", typeof(string));
    
            var mADVParameter = mADV != null ?
                new ObjectParameter("MADV", mADV) :
                new ObjectParameter("MADV", typeof(string));
    
            var nAMParameter = nAM.HasValue ?
                new ObjectParameter("NAM", nAM) :
                new ObjectParameter("NAM", typeof(int));
    
            var tHANGParameter = tHANG.HasValue ?
                new ObjectParameter("THANG", tHANG) :
                new ObjectParameter("THANG", typeof(int));
    
            var mAKHParameter = mAKH != null ?
                new ObjectParameter("MAKH", mAKH) :
                new ObjectParameter("MAKH", typeof(string));
    
            var nHAPKHOParameter = nHAPKHO != null ?
                new ObjectParameter("NHAPKHO", nHAPKHO) :
                new ObjectParameter("NHAPKHO", typeof(string));
    
            var lYDOSANXUATParameter = lYDOSANXUAT != null ?
                new ObjectParameter("LYDOSANXUAT", lYDOSANXUAT) :
                new ObjectParameter("LYDOSANXUAT", typeof(string));
    
            var mALOAICONGDOANParameter = mALOAICONGDOAN != null ?
                new ObjectParameter("MALOAICONGDOAN", mALOAICONGDOAN) :
                new ObjectParameter("MALOAICONGDOAN", typeof(string));
    
            var cONGDOANParameter = cONGDOAN != null ?
                new ObjectParameter("CONGDOAN", cONGDOAN) :
                new ObjectParameter("CONGDOAN", typeof(string));
    
            var mANVParameter = mANV != null ?
                new ObjectParameter("MANV", mANV) :
                new ObjectParameter("MANV", typeof(string));
    
            var mANV_XXParameter = mANV_XX != null ?
                new ObjectParameter("MANV_XX", mANV_XX) :
                new ObjectParameter("MANV_XX", typeof(string));
    
            var loaiYCSXParameter = loaiYCSX != null ?
                new ObjectParameter("LoaiYCSX", loaiYCSX) :
                new ObjectParameter("LoaiYCSX", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DMPHIEU_BANGKENHAPSOI_INSERT_211223", sOPHIEUParameter, mADVParameter, nAMParameter, tHANGParameter, mAKHParameter, nHAPKHOParameter, lYDOSANXUATParameter, mALOAICONGDOANParameter, cONGDOANParameter, mANVParameter, mANV_XXParameter, loaiYCSXParameter);
        }
    
        public virtual ObjectResult<VATTU2024_SPLOAD_GC_DMPHIEU_BANGKENHAPSOI_Result> VATTU2024_SPLOAD_GC_DMPHIEU_BANGKENHAPSOI(string sOPHIEU, string kEY)
        {
            var sOPHIEUParameter = sOPHIEU != null ?
                new ObjectParameter("SOPHIEU", sOPHIEU) :
                new ObjectParameter("SOPHIEU", typeof(string));
    
            var kEYParameter = kEY != null ?
                new ObjectParameter("KEY", kEY) :
                new ObjectParameter("KEY", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VATTU2024_SPLOAD_GC_DMPHIEU_BANGKENHAPSOI_Result>("VATTU2024_SPLOAD_GC_DMPHIEU_BANGKENHAPSOI", sOPHIEUParameter, kEYParameter);
        }
    
        public virtual ObjectResult<VATTU2024_SPLOAD_GC_CTPHIEUXUATGC_SUMSOLUONG_Result> VATTU2024_SPLOAD_GC_CTPHIEUXUATGC_SUMSOLUONG(string sOPHIEU, string kEY)
        {
            var sOPHIEUParameter = sOPHIEU != null ?
                new ObjectParameter("SOPHIEU", sOPHIEU) :
                new ObjectParameter("SOPHIEU", typeof(string));
    
            var kEYParameter = kEY != null ?
                new ObjectParameter("KEY", kEY) :
                new ObjectParameter("KEY", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VATTU2024_SPLOAD_GC_CTPHIEUXUATGC_SUMSOLUONG_Result>("VATTU2024_SPLOAD_GC_CTPHIEUXUATGC_SUMSOLUONG", sOPHIEUParameter, kEYParameter);
        }
    
        public virtual ObjectResult<VATTU2024_SPLOAD_DMNGUYENLIEUSOI_Result> VATTU2024_SPLOAD_DMNGUYENLIEUSOI()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VATTU2024_SPLOAD_DMNGUYENLIEUSOI_Result>("VATTU2024_SPLOAD_DMNGUYENLIEUSOI");
        }
    
        public virtual ObjectResult<VATTU2024_LOAD_DATA_MASOI_XUATKHO_THEO_XKNB_LOADMAPHIEUPD_Result> VATTU2024_LOAD_DATA_MASOI_XUATKHO_THEO_XKNB_LOADMAPHIEUPD(string mAHTHUC, string mAKHO, string mAVT)
        {
            var mAHTHUCParameter = mAHTHUC != null ?
                new ObjectParameter("MAHTHUC", mAHTHUC) :
                new ObjectParameter("MAHTHUC", typeof(string));
    
            var mAKHOParameter = mAKHO != null ?
                new ObjectParameter("MAKHO", mAKHO) :
                new ObjectParameter("MAKHO", typeof(string));
    
            var mAVTParameter = mAVT != null ?
                new ObjectParameter("MAVT", mAVT) :
                new ObjectParameter("MAVT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VATTU2024_LOAD_DATA_MASOI_XUATKHO_THEO_XKNB_LOADMAPHIEUPD_Result>("VATTU2024_LOAD_DATA_MASOI_XUATKHO_THEO_XKNB_LOADMAPHIEUPD", mAHTHUCParameter, mAKHOParameter, mAVTParameter);
        }
    
        public virtual ObjectResult<VATTU2024_DINHMUC_SOIGC_TONGSLVATTUCAN_Result> VATTU2024_DINHMUC_SOIGC_TONGSLVATTUCAN(string mASOIHOANTAT, string sophieu, Nullable<decimal> tONGSOLUONGSX)
        {
            var mASOIHOANTATParameter = mASOIHOANTAT != null ?
                new ObjectParameter("MASOIHOANTAT", mASOIHOANTAT) :
                new ObjectParameter("MASOIHOANTAT", typeof(string));
    
            var sophieuParameter = sophieu != null ?
                new ObjectParameter("sophieu", sophieu) :
                new ObjectParameter("sophieu", typeof(string));
    
            var tONGSOLUONGSXParameter = tONGSOLUONGSX.HasValue ?
                new ObjectParameter("TONGSOLUONGSX", tONGSOLUONGSX) :
                new ObjectParameter("TONGSOLUONGSX", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VATTU2024_DINHMUC_SOIGC_TONGSLVATTUCAN_Result>("VATTU2024_DINHMUC_SOIGC_TONGSLVATTUCAN", mASOIHOANTATParameter, sophieuParameter, tONGSOLUONGSXParameter);
        }
    
        public virtual ObjectResult<VATTU2024_SP_GC_DMPHIEU_CHITIETPHIEUXUAT_SUB_REPORT_Result> VATTU2024_SP_GC_DMPHIEU_CHITIETPHIEUXUAT_SUB_REPORT(string sOPHIEU)
        {
            var sOPHIEUParameter = sOPHIEU != null ?
                new ObjectParameter("SOPHIEU", sOPHIEU) :
                new ObjectParameter("SOPHIEU", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VATTU2024_SP_GC_DMPHIEU_CHITIETPHIEUXUAT_SUB_REPORT_Result>("VATTU2024_SP_GC_DMPHIEU_CHITIETPHIEUXUAT_SUB_REPORT", sOPHIEUParameter);
        }
    
        public virtual ObjectResult<VATTU2024_SP_GC_DMPHIEU_BANGKENHAPSOI_BY_SOPHIEU_REPORT_Result> VATTU2024_SP_GC_DMPHIEU_BANGKENHAPSOI_BY_SOPHIEU_REPORT(string sOPHIEU)
        {
            var sOPHIEUParameter = sOPHIEU != null ?
                new ObjectParameter("SOPHIEU", sOPHIEU) :
                new ObjectParameter("SOPHIEU", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VATTU2024_SP_GC_DMPHIEU_BANGKENHAPSOI_BY_SOPHIEU_REPORT_Result>("VATTU2024_SP_GC_DMPHIEU_BANGKENHAPSOI_BY_SOPHIEU_REPORT", sOPHIEUParameter);
        }
    
        public virtual ObjectResult<Insert_Invoice_NL_DMPHIEU_Review_Result> Insert_Invoice_NL_DMPHIEU_Review(string maphieu, string maphieupd, string sohopdong, string invoice, string tokhai, Nullable<decimal> gia, string quocgia, Nullable<System.DateTime> ngaynhaphang, string maspkhach, string makh, string userid)
        {
            var maphieuParameter = maphieu != null ?
                new ObjectParameter("maphieu", maphieu) :
                new ObjectParameter("maphieu", typeof(string));
    
            var maphieupdParameter = maphieupd != null ?
                new ObjectParameter("maphieupd", maphieupd) :
                new ObjectParameter("maphieupd", typeof(string));
    
            var sohopdongParameter = sohopdong != null ?
                new ObjectParameter("sohopdong", sohopdong) :
                new ObjectParameter("sohopdong", typeof(string));
    
            var invoiceParameter = invoice != null ?
                new ObjectParameter("invoice", invoice) :
                new ObjectParameter("invoice", typeof(string));
    
            var tokhaiParameter = tokhai != null ?
                new ObjectParameter("tokhai", tokhai) :
                new ObjectParameter("tokhai", typeof(string));
    
            var giaParameter = gia.HasValue ?
                new ObjectParameter("gia", gia) :
                new ObjectParameter("gia", typeof(decimal));
    
            var quocgiaParameter = quocgia != null ?
                new ObjectParameter("quocgia", quocgia) :
                new ObjectParameter("quocgia", typeof(string));
    
            var ngaynhaphangParameter = ngaynhaphang.HasValue ?
                new ObjectParameter("ngaynhaphang", ngaynhaphang) :
                new ObjectParameter("ngaynhaphang", typeof(System.DateTime));
    
            var maspkhachParameter = maspkhach != null ?
                new ObjectParameter("maspkhach", maspkhach) :
                new ObjectParameter("maspkhach", typeof(string));
    
            var makhParameter = makh != null ?
                new ObjectParameter("makh", makh) :
                new ObjectParameter("makh", typeof(string));
    
            var useridParameter = userid != null ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Insert_Invoice_NL_DMPHIEU_Review_Result>("Insert_Invoice_NL_DMPHIEU_Review", maphieuParameter, maphieupdParameter, sohopdongParameter, invoiceParameter, tokhaiParameter, giaParameter, quocgiaParameter, ngaynhaphangParameter, maspkhachParameter, makhParameter, useridParameter);
        }
    
        public virtual ObjectResult<SOI2024_SPLOAD_XVCNB_KETHUA_SOCTXN_Result> SOI2024_SPLOAD_XVCNB_KETHUA_SOCTXN(string makhoxuat)
        {
            var makhoxuatParameter = makhoxuat != null ?
                new ObjectParameter("makhoxuat", makhoxuat) :
                new ObjectParameter("makhoxuat", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SOI2024_SPLOAD_XVCNB_KETHUA_SOCTXN_Result>("SOI2024_SPLOAD_XVCNB_KETHUA_SOCTXN", makhoxuatParameter);
        }
    
        public virtual ObjectResult<VATTU2025_SPLOAD_KHOATHAMCHIEU_BANGKE_Result> VATTU2025_SPLOAD_KHOATHAMCHIEU_BANGKE(string kEY)
        {
            var kEYParameter = kEY != null ?
                new ObjectParameter("KEY", kEY) :
                new ObjectParameter("KEY", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VATTU2025_SPLOAD_KHOATHAMCHIEU_BANGKE_Result>("VATTU2025_SPLOAD_KHOATHAMCHIEU_BANGKE", kEYParameter);
        }
    
        public virtual ObjectResult<VATTU2025_SP_LOAD_DATA_SOIGIACONG_CHUAHOIKHO_GIAYBONG_Result> VATTU2025_SP_LOAD_DATA_SOIGIACONG_CHUAHOIKHO_GIAYBONG(string mAKHO, string mAVATTU)
        {
            var mAKHOParameter = mAKHO != null ?
                new ObjectParameter("MAKHO", mAKHO) :
                new ObjectParameter("MAKHO", typeof(string));
    
            var mAVATTUParameter = mAVATTU != null ?
                new ObjectParameter("MAVATTU", mAVATTU) :
                new ObjectParameter("MAVATTU", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VATTU2025_SP_LOAD_DATA_SOIGIACONG_CHUAHOIKHO_GIAYBONG_Result>("VATTU2025_SP_LOAD_DATA_SOIGIACONG_CHUAHOIKHO_GIAYBONG", mAKHOParameter, mAVATTUParameter);
        }
    
        public virtual ObjectResult<SOI2025_SPLOAD_SOCTXN_TANGGIAMKHO_NL_CTXUATNHAP_Result> SOI2025_SPLOAD_SOCTXN_TANGGIAMKHO_NL_CTXUATNHAP(string sOCTXN)
        {
            var sOCTXNParameter = sOCTXN != null ?
                new ObjectParameter("SOCTXN", sOCTXN) :
                new ObjectParameter("SOCTXN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SOI2025_SPLOAD_SOCTXN_TANGGIAMKHO_NL_CTXUATNHAP_Result>("SOI2025_SPLOAD_SOCTXN_TANGGIAMKHO_NL_CTXUATNHAP", sOCTXNParameter);
        }
    
        public virtual ObjectResult<VATTU2025_LOAD_PRINT_DATA_NHAPDIENGIAI_SOI_SOCTXN_Result> VATTU2025_LOAD_PRINT_DATA_NHAPDIENGIAI_SOI_SOCTXN(string sOCTXN)
        {
            var sOCTXNParameter = sOCTXN != null ?
                new ObjectParameter("SOCTXN", sOCTXN) :
                new ObjectParameter("SOCTXN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VATTU2025_LOAD_PRINT_DATA_NHAPDIENGIAI_SOI_SOCTXN_Result>("VATTU2025_LOAD_PRINT_DATA_NHAPDIENGIAI_SOI_SOCTXN", sOCTXNParameter);
        }
    
        public virtual ObjectResult<VATTU2025_SP_RPT_PHIEUDENGHIMUAHANG_PRINT_Result> VATTU2025_SP_RPT_PHIEUDENGHIMUAHANG_PRINT(string mAPHIEU, string userID)
        {
            var mAPHIEUParameter = mAPHIEU != null ?
                new ObjectParameter("MAPHIEU", mAPHIEU) :
                new ObjectParameter("MAPHIEU", typeof(string));
    
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VATTU2025_SP_RPT_PHIEUDENGHIMUAHANG_PRINT_Result>("VATTU2025_SP_RPT_PHIEUDENGHIMUAHANG_PRINT", mAPHIEUParameter, userIDParameter);
        }
    
        public virtual ObjectResult<VATTU2025_LOADTONKHO_THEOMAVT_SOI_Result> VATTU2025_LOADTONKHO_THEOMAVT_SOI(string mAVT, string hIEU)
        {
            var mAVTParameter = mAVT != null ?
                new ObjectParameter("MAVT", mAVT) :
                new ObjectParameter("MAVT", typeof(string));
    
            var hIEUParameter = hIEU != null ?
                new ObjectParameter("HIEU", hIEU) :
                new ObjectParameter("HIEU", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VATTU2025_LOADTONKHO_THEOMAVT_SOI_Result>("VATTU2025_LOADTONKHO_THEOMAVT_SOI", mAVTParameter, hIEUParameter);
        }
    
        public virtual ObjectResult<VATTU2026_UPDATE_STATUS_NL_DMPHIEUXN_Result> VATTU2026_UPDATE_STATUS_NL_DMPHIEUXN(string soct_xuat, string soct_nhap)
        {
            var soct_xuatParameter = soct_xuat != null ?
                new ObjectParameter("soct_xuat", soct_xuat) :
                new ObjectParameter("soct_xuat", typeof(string));
    
            var soct_nhapParameter = soct_nhap != null ?
                new ObjectParameter("soct_nhap", soct_nhap) :
                new ObjectParameter("soct_nhap", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VATTU2026_UPDATE_STATUS_NL_DMPHIEUXN_Result>("VATTU2026_UPDATE_STATUS_NL_DMPHIEUXN", soct_xuatParameter, soct_nhapParameter);
        }
    
        public virtual ObjectResult<VATTU2026_SP_RPT_BAOCAO_LICHSUXUATNHAP_NVLSOI_Result> VATTU2026_SP_RPT_BAOCAO_LICHSUXUATNHAP_NVLSOI(Nullable<System.DateTime> tUNGAY, Nullable<System.DateTime> dENNGAY, string mAKHO, string mAVT, string hIEU, string lO, string userID)
        {
            var tUNGAYParameter = tUNGAY.HasValue ?
                new ObjectParameter("TUNGAY", tUNGAY) :
                new ObjectParameter("TUNGAY", typeof(System.DateTime));
    
            var dENNGAYParameter = dENNGAY.HasValue ?
                new ObjectParameter("DENNGAY", dENNGAY) :
                new ObjectParameter("DENNGAY", typeof(System.DateTime));
    
            var mAKHOParameter = mAKHO != null ?
                new ObjectParameter("MAKHO", mAKHO) :
                new ObjectParameter("MAKHO", typeof(string));
    
            var mAVTParameter = mAVT != null ?
                new ObjectParameter("MAVT", mAVT) :
                new ObjectParameter("MAVT", typeof(string));
    
            var hIEUParameter = hIEU != null ?
                new ObjectParameter("HIEU", hIEU) :
                new ObjectParameter("HIEU", typeof(string));
    
            var lOParameter = lO != null ?
                new ObjectParameter("LO", lO) :
                new ObjectParameter("LO", typeof(string));
    
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VATTU2026_SP_RPT_BAOCAO_LICHSUXUATNHAP_NVLSOI_Result>("VATTU2026_SP_RPT_BAOCAO_LICHSUXUATNHAP_NVLSOI", tUNGAYParameter, dENNGAYParameter, mAKHOParameter, mAVTParameter, hIEUParameter, lOParameter, userIDParameter);
        }
    }
}
