//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.KhoSoi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_SoPYCXuatSoi
    {
        public string IDCode { get; set; }
        public string LoaiXN { get; set; }
        public string Kihieu { get; set; }
        public string NgayHT { get; set; }
        public string STT { get; set; }
        public string Sophieu { get; set; }
        public int ID { get; set; }
    }
}
