//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.KhoSoi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLDMNGUYENLIEU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLDMNGUYENLIEU()
        {
            this.NL_CTPHIEU = new HashSet<NL_CTPHIEU>();
            this.NL_CTXUATNHAP = new HashSet<NL_CTXUATNHAP>();
        }
    
        public decimal MAID { get; set; }
        public string MAVATTU { get; set; }
        public string Tenvattu { get; set; }
        public string MaNGL { get; set; }
        public string Ghichu { get; set; }
        public string CS1 { get; set; }
        public string CS2 { get; set; }
        public string DVT { get; set; }
        public Nullable<bool> isHieuluc { get; set; }
        public string MA2 { get; set; }
        public string Manhomvt { get; set; }
        public Nullable<decimal> Dongia { get; set; }
        public string TenVTat { get; set; }
        public string MANGL1 { get; set; }
        public Nullable<decimal> Tile1 { get; set; }
        public string MANGL2 { get; set; }
        public Nullable<decimal> Tile2 { get; set; }
        public string MANGL3 { get; set; }
        public Nullable<decimal> Tile3 { get; set; }
        public string MANGL4 { get; set; }
        public Nullable<decimal> Tile4 { get; set; }
        public string MANGL5 { get; set; }
        public Nullable<decimal> Tile5 { get; set; }
        public string Tenvattu_CUGC { get; set; }
        public string GuiAPI { get; set; }
        public Nullable<System.DateTime> NgayGuiAPI { get; set; }
        public string MANVCN { get; set; }
        public Nullable<System.DateTime> NGAYCN { get; set; }
        public string MANVMODIFY { get; set; }
        public Nullable<System.DateTime> NGAYMODIFY { get; set; }
        public string ASSET { get; set; }
        public string COGS { get; set; }
        public string INCOME { get; set; }
        public string MACP { get; set; }
        public string LoaiSoi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NL_CTPHIEU> NL_CTPHIEU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NL_CTXUATNHAP> NL_CTXUATNHAP { get; set; }
    }
}
