//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.NhuomAH
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QLSX_Nhuom_AnhHongEntities : DbContext
    {
        public QLSX_Nhuom_AnhHongEntities()
            : base("name=QLSX_Nhuom_AnhHongEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<NOILAYHOACHAT> NOILAYHOACHATs { get; set; }
        public virtual DbSet<XuatHCTN_theotruc> XuatHCTN_theotruc { get; set; }
    
        public virtual ObjectResult<Spload_tblCongDoan_Result> Spload_tblCongDoan()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Spload_tblCongDoan_Result>("Spload_tblCongDoan");
        }
    
        public virtual ObjectResult<SPLOAD_XUATHCTN_THEOTRUC_Result> SPLOAD_XUATHCTN_THEOTRUC(string mACD, string mAMH, string kEY)
        {
            var mACDParameter = mACD != null ?
                new ObjectParameter("MACD", mACD) :
                new ObjectParameter("MACD", typeof(string));
    
            var mAMHParameter = mAMH != null ?
                new ObjectParameter("MAMH", mAMH) :
                new ObjectParameter("MAMH", typeof(string));
    
            var kEYParameter = kEY != null ?
                new ObjectParameter("KEY", kEY) :
                new ObjectParameter("KEY", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPLOAD_XUATHCTN_THEOTRUC_Result>("SPLOAD_XUATHCTN_THEOTRUC", mACDParameter, mAMHParameter, kEYParameter);
        }
    }
}
