//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.VatTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHATLUONG
    {
        public string SOCT { get; set; }
        public Nullable<System.DateTime> NGAYKHO { get; set; }
        public Nullable<System.DateTime> NGAYKT { get; set; }
        public string THUKHO { get; set; }
        public string GDDV { get; set; }
        public Nullable<bool> KHOXN { get; set; }
        public Nullable<bool> DVXN { get; set; }
        public Nullable<bool> DaIn { get; set; }
        public byte FlagXoa { get; set; }
        public Nullable<bool> DVKT { get; set; }
    }
}
