//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.VatTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chatluong_NL
    {
        public string SoCTXN { get; set; }
        public Nullable<System.DateTime> NgayKho { get; set; }
        public Nullable<System.DateTime> NgayKT { get; set; }
        public string ThuKho { get; set; }
        public string GDDV { get; set; }
        public Nullable<bool> KhoXN { get; set; }
        public Nullable<bool> DVXN { get; set; }
        public Nullable<bool> DaIn { get; set; }
        public Nullable<byte> FlagXoa { get; set; }
    }
}
