//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.VatTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETPHIEUCHAOGIA
    {
        public string MAPHIEUCHAOGIA { get; set; }
        public string DONVICUNGCAP { get; set; }
        public Nullable<int> STT { get; set; }
        public string NHANHIEU { get; set; }
        public string XUATXU { get; set; }
        public Nullable<System.DateTime> THOIHANGIAOHANG { get; set; }
        public string QUICACHDONGGOI { get; set; }
        public string THANHTOAN { get; set; }
        public string CHATLUONGHANG { get; set; }
        public string TIEUCHANKYTHUAT { get; set; }
        public string KHAC { get; set; }
        public string IDChiTiet { get; set; }
        public string DONGIACHAO { get; set; }
    }
}
