//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.VatTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTPhieu_CDMH
    {
        public string Maphieu { get; set; }
        public string MAVT { get; set; }
        public decimal w01_SLYC { get; set; }
        public decimal w02_SLYC { get; set; }
        public decimal nmn_SLYC { get; set; }
        public decimal qua_SLYC { get; set; }
        public decimal rnd_SLYC { get; set; }
        public decimal CU_SLCD { get; set; }
        public string CU_Lydo { get; set; }
        public decimal BTGD_SLPD { get; set; }
        public string BTGD_Ghichu { get; set; }
        public Nullable<decimal> TonkhokhiKiemTra { get; set; }
        public Nullable<bool> CU_Static { get; set; }
        public Nullable<bool> BTGD_Static { get; set; }
    
        public virtual DMPhieu_CDMH DMPhieu_CDMH { get; set; }
    }
}
