//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.VatTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTPHIEU05
    {
        public Nullable<decimal> STT { get; set; }
        public string MASOCP { get; set; }
        public string MAPHIEU { get; set; }
        public string MAVT { get; set; }
        public Nullable<decimal> SLYCAU { get; set; }
        public Nullable<decimal> SLXXet { get; set; }
        public Nullable<decimal> SLPD { get; set; }
        public Nullable<decimal> SLTonDVi { get; set; }
        public string TinhTrang { get; set; }
        public Nullable<System.DateTime> ThoiDiemSD { get; set; }
        public string GhiChu { get; set; }
        public string MaNV { get; set; }
        public string NhanVienLapPhieu { get; set; }
        public string MaBP { get; set; }
        public Nullable<System.DateTime> NGAYNHAP { get; set; }
        public Nullable<System.DateTime> NGAYXX { get; set; }
        public string DACTINHKYTHUAT { get; set; }
        public int ID_INT { get; set; }
    
        public virtual DANHMUCVATTU DANHMUCVATTU { get; set; }
        public virtual DMPHIEU DMPHIEU { get; set; }
    }
}
