//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.VatTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTPHIEU
    {
        public Nullable<decimal> STT { get; set; }
        public string MASOCP { get; set; }
        public string MAPHIEU { get; set; }
        public string MAVT { get; set; }
        public string MAVT_TUONGDUONG { get; set; }
        public Nullable<decimal> SLYCAU { get; set; }
        public Nullable<decimal> SLXXET { get; set; }
        public Nullable<decimal> SLPD { get; set; }
        public Nullable<decimal> SLTONDVI { get; set; }
        public Nullable<decimal> SLTONCTY { get; set; }
        public string TINHTRANG { get; set; }
        public Nullable<System.DateTime> THOIDIEMSD { get; set; }
        public string GHICHU { get; set; }
        public Nullable<System.DateTime> THOIDIEMDAPUNG { get; set; }
        public string YKIENLANHDAO { get; set; }
        public string MaphieuchuyenNB { get; set; }
        public string MADH { get; set; }
        public string DACTINHKYTHUAT { get; set; }
        public int IDKHOA { get; set; }
        public Nullable<bool> IsLOT { get; set; }
        public string SoPONetSuite { get; set; }
        public string InternalIDNetSuite { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public string Currency { get; set; }
        public Nullable<System.DateTime> Expected_Receipt_Date { get; set; }
        public Nullable<decimal> TIGIA { get; set; }
        public string PHTinhTrangKyThuatCU { get; set; }
        public Nullable<System.DateTime> TgianNhaMayPHCU { get; set; }
        public string PHTinhTrangNCC { get; set; }
        public string PHTinhTrangThanhtoan { get; set; }
        public Nullable<System.DateTime> PHHanThanhToan { get; set; }
        public Nullable<System.DateTime> PHDapUngCU { get; set; }
        public Nullable<System.DateTime> PHTienDoDapUngThucTeCU { get; set; }
        public string TinhTrangDapUngCU { get; set; }
        public string LyDoTreHanCU { get; set; }
        public string MANVMuaHang { get; set; }
        public string GhiChuCUng { get; set; }
    
        public virtual DMPHIEU DMPHIEU { get; set; }
    }
}
