//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.VatTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANHMUCVATTU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DANHMUCVATTU()
        {
            this.DMGIATRIVATTUs = new HashSet<DMGIATRIVATTU>();
            this.TONDAUKies = new HashSet<TONDAUKY>();
            this.CTPHIEU05 = new HashSet<CTPHIEU05>();
        }
    
        public string MAVT { get; set; }
        public string TenVT { get; set; }
        public string DVT { get; set; }
        public string LoaiVT { get; set; }
        public string MACP { get; set; }
        public string DonViSuDungtac { get; set; }
        public string ViTriDe { get; set; }
        public Nullable<decimal> DinhMucToiUu { get; set; }
        public Nullable<bool> HieuLuc { get; set; }
        public string MaNGL { get; set; }
        public string Ghichu { get; set; }
        public string CS1 { get; set; }
        public string CS2 { get; set; }
        public string MA2 { get; set; }
        public string Manhom { get; set; }
        public string TenVTat { get; set; }
        public string Images { get; set; }
        public string Images_v2 { get; set; }
        public Nullable<int> HANDAPUNG { get; set; }
        public Nullable<System.DateTime> NGAYCN { get; set; }
        public string NHOM_GC { get; set; }
        public string MANVCAPNHAT { get; set; }
        public string MANVMODIFY { get; set; }
        public Nullable<System.DateTime> NGAYMODIFY { get; set; }
        public string GuiAPI { get; set; }
        public Nullable<System.DateTime> NgayGuiAPI { get; set; }
        public string COGS { get; set; }
        public string ASSET { get; set; }
        public string INCOME { get; set; }
        public string TK_ChiPhi_SX { get; set; }
    
        public virtual DANHMUCDONVITINH DANHMUCDONVITINH { get; set; }
        public virtual DMViTri DMViTri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DMGIATRIVATTU> DMGIATRIVATTUs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TONDAUKY> TONDAUKies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTPHIEU05> CTPHIEU05 { get; set; }
    }
}
