//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.VatTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANHMUCDONVITINH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DANHMUCDONVITINH()
        {
            this.DANHMUCVATTUs = new HashSet<DANHMUCVATTU>();
        }
    
        public string FMaDVT { get; set; }
        public string TenGoi { get; set; }
        public string KiHieu { get; set; }
        public string CachTinh { get; set; }
        public string KyHieuKho { get; set; }
        public string CTQDDVKg { get; set; }
        public string CTQDDVMet { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANHMUCVATTU> DANHMUCVATTUs { get; set; }
    }
}
