//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.VatTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANHMUCQUYEN
    {
        public string KIHIEU { get; set; }
        public string MAKHO { get; set; }
        public byte QuyenLP { get; set; }
        public byte QuyenX { get; set; }
        public byte QuyenN { get; set; }
        public string MANV { get; set; }
    }
}
