//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.VatTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_TinhTrangKyThuatCUGC
    {
        public string Ma_tinhtrangkythuat { get; set; }
        public string Ten_tinhtrangkythuat { get; set; }
    }
}
