//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.VatTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_XUATNHAP
    {
        public int STT { get; set; }
        public string SOCTXN { get; set; }
        public string MADH { get; set; }
        public Nullable<System.DateTime> NGAY { get; set; }
        public string LOAIXN { get; set; }
        public string MaNVYC { get; set; }
        public string MANVXUAT { get; set; }
        public string IDMADVNHAN { get; set; }
        public string MAKHONHAN { get; set; }
        public string NGUOINHAN { get; set; }
        public string GHICHU { get; set; }
        public string IDMADVXUAT { get; set; }
        public string MAKHOXUAT { get; set; }
        public string NGUOIXUAT { get; set; }
        public string KETHUATUSOCT { get; set; }
        public Nullable<bool> DAXUATKHO_ { get; set; }
        public string GUIAPI { get; set; }
        public Nullable<System.DateTime> NGAYGUIAPI { get; set; }
        public string MANVCN { get; set; }
        public Nullable<System.DateTime> NGAYCN { get; set; }
        public string MANVMODIFY { get; set; }
        public Nullable<System.DateTime> NGAYMODIFY { get; set; }
        public string NHACUNGCAP { get; set; }
        public string SOPO { get; set; }
        public string InternalidPO { get; set; }
        public string Externalid_IAD { get; set; }
        public string kyhieu { get; set; }
        public string Sohoadon { get; set; }
        public string Duonglink { get; set; }
        public byte[] Hinhhoadon { get; set; }
        public string MANVXX { get; set; }
        public Nullable<bool> ISXEMXET { get; set; }
    }
}
