//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.VatTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMDONVI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DMDONVI()
        {
            this.OLDs = new HashSet<OLD>();
            this.TBLDMCAPCOSOes = new HashSet<TBLDMCAPCOSO>();
        }
    
        public string IDMaDV { get; set; }
        public string MaDonVi { get; set; }
        public string MADV_NETSUITE { get; set; }
        public string TenDonVi { get; set; }
        public string KiHieu_New { get; set; }
        public string KiHieu { get; set; }
        public Nullable<byte> HieuLuc { get; set; }
        public string TenGiaoDich_DV { get; set; }
        public string DiaChi_DV { get; set; }
        public string SoDienThoai_DV { get; set; }
        public string Fax_DV { get; set; }
        public Nullable<bool> Thanhpham_Xuat { get; set; }
        public Nullable<bool> Thanhpham_Nhap { get; set; }
        public Nullable<bool> Moc_Nhap { get; set; }
        public Nullable<bool> Moc_Xuat { get; set; }
        public Nullable<bool> BPDatbong { get; set; }
        public Nullable<bool> DONHANGNHUOM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OLD> OLDs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLDMCAPCOSO> TBLDMCAPCOSOes { get; set; }
    }
}
