//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.VatTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMGIATRIVATTU
    {
        public string NAM { get; set; }
        public string THANG { get; set; }
        public string MAVT { get; set; }
        public string MAKHO { get; set; }
        public decimal DONGIATON { get; set; }
        public bool HIEULUC { get; set; }
        public string GHICHU { get; set; }
        public System.DateTime NGAYCN { get; set; }
        public string NGUOINHAP { get; set; }
        public Nullable<System.DateTime> NGAYNHAP { get; set; }
    
        public virtual DMKHo DMKHo { get; set; }
        public virtual DANHMUCVATTU DANHMUCVATTU { get; set; }
    }
}
