//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.VatTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMKHONHAN
    {
        public string MAKHONHAN { get; set; }
        public string TENKHONHAN { get; set; }
        public string DIACHI { get; set; }
        public string LOAIXN { get; set; }
        public string MANVCN { get; set; }
        public Nullable<System.DateTime> NGAYCN { get; set; }
        public string MANVMODIFY { get; set; }
        public Nullable<System.DateTime> NGAYMODIFY { get; set; }
        public Nullable<bool> hieuluc { get; set; }
        public string Nguoinhan { get; set; }
    }
}
