//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.VatTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMKHo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DMKHo()
        {
            this.DMGIATRIVATTUs = new HashSet<DMGIATRIVATTU>();
            this.DMVITRIKHOes = new HashSet<DMVITRIKHO>();
            this.TONDAUKies = new HashSet<TONDAUKY>();
        }
    
        public string MAKHO { get; set; }
        public string MAKHONETSUITe { get; set; }
        public string TENKHO { get; set; }
        public string MAKHOKETOAN { get; set; }
        public string NHOM_OGSTM { get; set; }
        public string DV_OGSTM { get; set; }
        public string DIACHI { get; set; }
        public string KHONHAN { get; set; }
        public Nullable<bool> XUATNOIBO { get; set; }
        public string ThuKho { get; set; }
        public string Loaiphieu { get; set; }
        public Nullable<bool> hieuluc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DMGIATRIVATTU> DMGIATRIVATTUs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DMVITRIKHO> DMVITRIKHOes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TONDAUKY> TONDAUKies { get; set; }
    }
}
