//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.VatTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMLOAIVT
    {
        public Nullable<int> STT { get; set; }
        public string LoaiVT { get; set; }
        public string Kytudautien { get; set; }
        public string TenLoai { get; set; }
        public Nullable<byte> HieuLuc { get; set; }
        public string Donvisd { get; set; }
        public string LoaiPhieu { get; set; }
        public Nullable<bool> VanChuyenNB { get; set; }
        public string LOAIVT_HDDT { get; set; }
        public string Donvisd04 { get; set; }
    
        public virtual DanhmucLoaiVT DanhmucLoaiVT { get; set; }
    }
}
