//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.VatTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMLOAIXN
    {
        public string LOAIXN { get; set; }
        public string TEN { get; set; }
        public Nullable<bool> Giaybong { get; set; }
        public string Xuat1buoc3buoc { get; set; }
        public Nullable<bool> HieuLuc { get; set; }
        public Nullable<decimal> STT { get; set; }
        public string Account_IAD { get; set; }
        public string Nguon_goc { get; set; }
    }
}
