//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.VatTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMPhieu_CDMH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DMPhieu_CDMH()
        {
            this.CTPhieu_CDMH = new HashSet<CTPhieu_CDMH>();
        }
    
        public string Maphieu { get; set; }
        public System.DateTime Ngaylapphieu { get; set; }
        public bool PDuyet { get; set; }
        public bool Tiepnhan { get; set; }
        public Nullable<System.DateTime> NgayPD { get; set; }
        public Nullable<System.DateTime> NgayTiepNhan { get; set; }
        public string Ghichu { get; set; }
        public bool Hieuluc { get; set; }
        public string NguoiLP { get; set; }
        public bool Kiemtra { get; set; }
        public System.DateTime Modified { get; set; }
        public string NguoiPD { get; set; }
        public string NguoiKiemtra { get; set; }
        public Nullable<System.DateTime> NgayKiemtra { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTPhieu_CDMH> CTPhieu_CDMH { get; set; }
    }
}
