//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.VatTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMPHIEU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DMPHIEU()
        {
            this.CTPHIEUx = new HashSet<CTPHIEU>();
            this.CTPHIEU05 = new HashSet<CTPHIEU05>();
        }
    
        public Nullable<decimal> STT { get; set; }
        public string MAPHIEU { get; set; }
        public Nullable<System.DateTime> NgayYC { get; set; }
        public string NguoiPD { get; set; }
        public string NguoiXX { get; set; }
        public string NguoiTiepNhan { get; set; }
        public string NguoiLapPhieu { get; set; }
        public string LyDoSD { get; set; }
        public string Nam { get; set; }
        public Nullable<decimal> STTPD { get; set; }
        public string MaPhieuPD { get; set; }
        public string LOAIPHIEU { get; set; }
        public Nullable<byte> DX { get; set; }
        public Nullable<byte> NK { get; set; }
        public Nullable<byte> ND { get; set; }
        public Nullable<byte> KH { get; set; }
        public Nullable<byte> HieuLuc { get; set; }
        public string KyHieu { get; set; }
        public Nullable<System.DateTime> NgayXX { get; set; }
        public Nullable<System.DateTime> NgayPD { get; set; }
        public Nullable<System.DateTime> NgayTN { get; set; }
        public Nullable<byte> XXet { get; set; }
        public Nullable<byte> PDuyet { get; set; }
        public Nullable<byte> TNhanYC { get; set; }
        public Nullable<System.DateTime> KEHOACHTHANG { get; set; }
        public string LoaiVT { get; set; }
        public Nullable<int> NumberCheck { get; set; }
        public Nullable<bool> FinishCheck { get; set; }
        public string locations { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTPHIEU> CTPHIEUx { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTPHIEU05> CTPHIEU05 { get; set; }
        public virtual DMLOAIPHIEU DMLOAIPHIEU { get; set; }
    }
}
