//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.VatTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMSitesQLKhoSoi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DMSitesQLKhoSoi()
        {
            this.PhanQuyenSitesQLKhoSois = new HashSet<PhanQuyenSitesQLKhoSoi>();
        }
    
        public int ID { get; set; }
        public string Sites { get; set; }
        public string DienGiai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhanQuyenSitesQLKhoSoi> PhanQuyenSitesQLKhoSois { get; set; }
    }
}
