//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.VatTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class dmVitriTang
    {
        public string Khoa2 { get; set; }
        public string MATANG { get; set; }
        public string TENTANG { get; set; }
        public Nullable<bool> HIEULUC { get; set; }
        public string Khoa1 { get; set; }
    
        public virtual dmVitriKe dmVitriKe { get; set; }
    }
}
