//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.VatTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class dmVitriKe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dmVitriKe()
        {
            this.dmVitriTangs = new HashSet<dmVitriTang>();
        }
    
        public string Khoa1 { get; set; }
        public string MAKE { get; set; }
        public string TENKE { get; set; }
        public Nullable<bool> HIEULUC { get; set; }
        public string Khoa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dmVitriTang> dmVitriTangs { get; set; }
    }
}
