//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.VatTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMVITRIKHO
    {
        public string MAKHO { get; set; }
        public string MASOKE { get; set; }
        public string MASOVITRI { get; set; }
        public string TEN { get; set; }
        public string GHICHU { get; set; }
        public bool HIEULUC { get; set; }
        public string KHOA { get; set; }
    
        public virtual DMKHo DMKHo { get; set; }
    }
}
