//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.VatTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMVT_Excel
    {
        public string MAVT { get; set; }
        public string TenVT { get; set; }
        public string LoaiVT { get; set; }
        public string DVT { get; set; }
        public string DonViSuDungtac { get; set; }
        public string ViTriDe { get; set; }
        public string Ghichu { get; set; }
        public string NHOM_GC { get; set; }
        public string MACP { get; set; }
    }
}
