//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.VatTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class GHNGAYNHAPKHO
    {
        public byte NK { get; set; }
        public byte ND { get; set; }
        public float GHansongaynhap { get; set; }
        public string Ghichu { get; set; }
        public Nullable<byte> hieuluc { get; set; }
    }
}
