//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.VatTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIAYBONG_XUATNHAP
    {
        public System.Guid ID { get; set; }
        public string SoCTXN { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public string LoaiXN { get; set; }
        public string DonViYeuCau { get; set; }
        public string MaNVYC { get; set; }
        public string MaKho { get; set; }
        public string MAVT { get; set; }
        public Nullable<decimal> SoLuong { get; set; }
        public Nullable<decimal> SoLuongTT { get; set; }
        public string NhanVienXuat { get; set; }
        public Nullable<System.DateTime> NgayXuat { get; set; }
        public string GhiChu { get; set; }
        public Nullable<byte> DaXuatKho { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string LastModifiedByID { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
    }
}
