//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.VatTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class InNhan
    {
        public int ID { get; set; }
        public string InNhanID { get; set; }
        public string Mahang { get; set; }
        public Nullable<decimal> SoLanIn { get; set; }
        public string Nhomhang { get; set; }
        public string Duoigoc { get; set; }
        public Nullable<decimal> Solabong { get; set; }
        public Nullable<decimal> Mnmoc { get; set; }
        public Nullable<decimal> mndoc { get; set; }
        public Nullable<decimal> Khomacluoc { get; set; }
        public Nullable<decimal> khomoc { get; set; }
        public string MahangTN { get; set; }
        public string Manhommay { get; set; }
        public string Mahang2 { get; set; }
        public Nullable<decimal> Cohaohutnhuom { get; set; }
        public string GTDet { get; set; }
        public string GTNhuom { get; set; }
        public Nullable<decimal> MnTP { get; set; }
        public Nullable<decimal> tlgm2 { get; set; }
        public Nullable<decimal> dsgm2duong { get; set; }
        public Nullable<decimal> dsgm2am { get; set; }
        public string dvtds { get; set; }
        public Nullable<decimal> khotp { get; set; }
        public bool hieulucHC { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
    }
}
