//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.VatTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHOSOI_XUATNHAP
    {
        public string Khoa { get; set; }
        public string Mavt { get; set; }
        public string Lo { get; set; }
        public string Hieu { get; set; }
        public Nullable<decimal> Soluong { get; set; }
        public Nullable<int> LanXN { get; set; }
        public Nullable<System.DateTime> NgayCN { get; set; }
    }
}
