//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.VatTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class KYDUYET_PHIEUCHAOGIA
    {
        public string MAPHIEUCHAOGIA { get; set; }
        public string NOIDUNG { get; set; }
        public string MANVCN { get; set; }
        public Nullable<int> STT { get; set; }
        public string KHOA { get; set; }
    }
}
