//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.VatTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class LDD_DMPHIEU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LDD_DMPHIEU()
        {
            this.LDD_CTPHIEU = new HashSet<LDD_CTPHIEU>();
        }
    
        public decimal STT { get; set; }
        public string MAPHIEU { get; set; }
        public Nullable<int> SO { get; set; }
        public Nullable<System.DateTime> NGAYLAP { get; set; }
        public Nullable<System.DateTime> NGAYDI { get; set; }
        public string MANV { get; set; }
        public string NOIDI { get; set; }
        public string NOIDEN { get; set; }
        public string DONVIVANCHUYEN { get; set; }
        public string PHUONGTIENVANCHUYEN { get; set; }
        public string TENTAIXE { get; set; }
        public string NOIDUNG { get; set; }
        public string SOCTXN { get; set; }
        public string MABP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LDD_CTPHIEU> LDD_CTPHIEU { get; set; }
        public virtual LDD_DMNOIDEN LDD_DMNOIDEN { get; set; }
    }
}
