//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.VatTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class LDD_CTPHIEU
    {
        public string MAPHIEU { get; set; }
        public string MAVT { get; set; }
        public Nullable<decimal> SOLUONGTT { get; set; }
        public Nullable<decimal> SOLUONGXUAT { get; set; }
        public string GHICHU { get; set; }
        public string KHOAKEYXN { get; set; }
    
        public virtual LDD_DMPHIEU LDD_DMPHIEU { get; set; }
    }
}
