//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.VatTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class LDD_DMNOIDEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LDD_DMNOIDEN()
        {
            this.LDD_DMPHIEU = new HashSet<LDD_DMPHIEU>();
        }
    
        public string MAKH { get; set; }
        public string NOIDEN { get; set; }
        public Nullable<bool> HIEULUC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LDD_DMPHIEU> LDD_DMPHIEU { get; set; }
    }
}
