//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.VatTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class NGANG_V2
    {
        public string MAHANG { get; set; }
        public string TENVT { get; set; }
        public string Trongluong { get; set; }
        public string matdo { get; set; }
        public string khotp { get; set; }
        public string Mathanhphan { get; set; }
        public string Manvcapnhat { get; set; }
        public Nullable<System.DateTime> Ngaycapnhat { get; set; }
        public string Manvmodify { get; set; }
        public Nullable<System.DateTime> Ngaymodify { get; set; }
        public Nullable<bool> Hieuluc { get; set; }
        public string Ghichu { get; set; }
    }
}
