//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.VatTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHAPDIENGIAI
    {
        public string KEYNHAP { get; set; }
        public string SOCTXN { get; set; }
        public string SOCTKETOAN { get; set; }
        public string MAVT { get; set; }
        public string TENVATTU_NCC { get; set; }
        public decimal SOLUONG_NCC { get; set; }
        public string DVT_NCC { get; set; }
        public Nullable<System.DateTime> NGAY_NCC { get; set; }
        public string MAPHIEUPD { get; set; }
        public string KHOAKEYXN { get; set; }
    }
}
