//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.VatTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHANQUYENSITESQLVT
    {
        public int ID { get; set; }
        public string MaNV { get; set; }
        public int IDSites { get; set; }
        public Nullable<bool> NoAccess { get; set; }
        public Nullable<bool> OnlyRead { get; set; }
        public Nullable<bool> AccessAll { get; set; }
        public string NguoiUy { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public Nullable<bool> ISKhongKiemTraIP { get; set; }
        public string Sites { get; set; }
    }
}
