//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.VatTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanQuyenSitesQLKhoSoi
    {
        public int ID { get; set; }
        public string MaNV { get; set; }
        public Nullable<int> IDSites { get; set; }
        public Nullable<byte> NoAccess { get; set; }
        public Nullable<byte> OnlyRead { get; set; }
        public Nullable<byte> AccessAll { get; set; }
        public string NguoiUy { get; set; }
    
        public virtual DMSitesQLKhoSoi DMSitesQLKhoSoi { get; set; }
    }
}
