//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.VatTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class TABLE_LUUTRU_SOHOADON
    {
        public int ID_SOCTXN { get; set; }
        public string SOCTXN { get; set; }
        public string PO { get; set; }
        public string PR { get; set; }
        public string kyhieuhoadon { get; set; }
        public string sohoadon { get; set; }
        public string LinkHD { get; set; }
        public string TenHinhAnh { get; set; }
        public byte[] HinhAnh { get; set; }
        public string FileNamePDF { get; set; }
        public string ContentTypePDF { get; set; }
        public byte[] FileDataPDF { get; set; }
        public Nullable<int> THANG { get; set; }
        public Nullable<int> NAM { get; set; }
        public string LoaiPhieu { get; set; }
        public string Thumuc { get; set; }
        public Nullable<System.DateTime> NGAYKHAI { get; set; }
        public string TOKHAI { get; set; }
        public string MST { get; set; }
        public string XUATXU { get; set; }
        public string NgoaiTe { get; set; }
        public Nullable<decimal> TyGia_NgoaiTe { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.DateTime> NGAYHD { get; set; }
        public string MANVCN { get; set; }
        public Nullable<System.DateTime> NGAYCN { get; set; }
    }
}
