//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.VatTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DMLOAIVT_COA
    {
        public string NVL { get; set; }
        public string TenNVL { get; set; }
        public string LoaiVT { get; set; }
        public string TenLoaiVT { get; set; }
        public string ManhomVT { get; set; }
        public string TenNhomVT { get; set; }
        public string Kytu_theonhom { get; set; }
        public Nullable<int> Len_kytu { get; set; }
        public string MACP { get; set; }
        public string ASSET { get; set; }
        public string Name_Asset { get; set; }
        public string TK_PhiSX { get; set; }
        public string Name_TK_PhiSX { get; set; }
        public string COGS { get; set; }
        public string Name_COGS { get; set; }
        public string INCOME { get; set; }
        public string Name_INCOME { get; set; }
        public Nullable<bool> HIEULUC { get; set; }
        public int INT { get; set; }
        public string WIPSTATUS { get; set; }
        public string CustomForm { get; set; }
        public int ID_INT { get; set; }
    }
}
