//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.VatTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PHIENMAVT_BYMAHANG
    {
        public string SOCTXUAT_VAI { get; set; }
        public string MAHANGVAI { get; set; }
        public string MACAY { get; set; }
        public string DVT_VAI { get; set; }
        public Nullable<decimal> SOLUONG { get; set; }
        public string MAVT { get; set; }
        public string DVT_MAVT { get; set; }
        public Nullable<decimal> SOLUONGTT { get; set; }
        public string MANVCN { get; set; }
        public Nullable<System.DateTime> NGAYCN { get; set; }
        public string MANVMODIFY { get; set; }
        public Nullable<System.DateTime> NGAYMODIFY { get; set; }
        public System.Guid ID_PHIEN { get; set; }
        public string KEYKHOA { get; set; }
    }
}
