//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.VatTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DMCHUKY
    {
        public string MANV { get; set; }
        public string HOTEN { get; set; }
        public string VITRICV { get; set; }
        public Nullable<decimal> MAQUYEN { get; set; }
        public Nullable<bool> HIEULUC { get; set; }
        public byte[] CHUKY { get; set; }
    }
}
