//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.VatTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLDMMAHANG
    {
        public string MAHANG { get; set; }
        public string NHOMHANG { get; set; }
        public string DUOIGOC { get; set; }
        public Nullable<decimal> SOLABONG { get; set; }
        public Nullable<decimal> MNMOC { get; set; }
        public Nullable<decimal> MNDOC { get; set; }
        public Nullable<decimal> KHOMACLUOC { get; set; }
        public Nullable<decimal> KHOMOC { get; set; }
        public string MAHANGTN { get; set; }
        public string MANHOMMAY { get; set; }
        public string MAHANG2 { get; set; }
        public Nullable<decimal> COHAOHUTNHUOM { get; set; }
        public string GTDET { get; set; }
        public string GTNHUOM { get; set; }
        public Nullable<decimal> MNTP { get; set; }
        public Nullable<decimal> TLGM2 { get; set; }
        public Nullable<decimal> DSGM2DUONG { get; set; }
        public Nullable<decimal> DSGM2AM { get; set; }
        public string DVTDS { get; set; }
        public Nullable<decimal> KHOTP { get; set; }
        public bool HIEULUCHC { get; set; }
        public Nullable<System.DateTime> NGAYCN { get; set; }
        public string NGUOICN { get; set; }
    }
}
