//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.VatTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLDMCAPCOSO
    {
        public string MADVI { get; set; }
        public string MABP { get; set; }
        public int STTBP { get; set; }
        public string MADV_NETSUITE { get; set; }
        public string MABP_NETSUITE { get; set; }
        public string TENGOI { get; set; }
        public string KihieuBP { get; set; }
        public Nullable<bool> hieuluc { get; set; }
        public string IDMaCS { get; set; }
        public string IDMaDV { get; set; }
        public string TengoiCTNS { get; set; }
        public string TenGiaoDich_CS { get; set; }
        public string DiaChi_CS { get; set; }
        public string SoDienThoai_CS { get; set; }
        public string Fax_CS { get; set; }
        public Nullable<bool> Thanhpham_Xuat { get; set; }
        public Nullable<bool> Thanhpham_Nhap { get; set; }
        public Nullable<bool> BPDatbong { get; set; }
        public string NhomBP { get; set; }
        public string MANV_XEMXET { get; set; }
        public Nullable<bool> MADHNHUOM { get; set; }
    
        public virtual DMDONVI DMDONVI { get; set; }
    }
}
