//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.VatTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDMNGUYENLIEUOLD
    {
        public string MAID { get; set; }
        public string Mavattu { get; set; }
        public string Tenvattu { get; set; }
        public string MaNGL { get; set; }
        public string Ghichu { get; set; }
        public string CS1 { get; set; }
        public string CS2 { get; set; }
        public string DVT { get; set; }
        public Nullable<int> isHieuluc { get; set; }
        public string MA2 { get; set; }
        public string Manhomvt { get; set; }
        public Nullable<decimal> Dongia { get; set; }
        public string TenVTat { get; set; }
    }
}
