//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.VatTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDMNGUYENLIEU
    {
        public decimal MAID { get; set; }
        public string Mavattu { get; set; }
        public string Tenvattu { get; set; }
        public string MaNGL { get; set; }
        public string Ghichu { get; set; }
        public string CS1 { get; set; }
        public string CS2 { get; set; }
        public string DVT { get; set; }
        public Nullable<int> isHieuluc { get; set; }
        public string MA2 { get; set; }
        public string Manhomvt { get; set; }
        public Nullable<decimal> Dongia { get; set; }
        public string TenVTat { get; set; }
        public Nullable<System.DateTime> Ngaycn { get; set; }
        public string MANGL1 { get; set; }
        public Nullable<decimal> Tile1 { get; set; }
        public string MANGL2 { get; set; }
        public Nullable<decimal> Tile2 { get; set; }
        public string MANGL3 { get; set; }
        public Nullable<decimal> Tile3 { get; set; }
        public string MANGL4 { get; set; }
        public Nullable<decimal> Tile4 { get; set; }
        public string MANGL5 { get; set; }
        public Nullable<decimal> Tile5 { get; set; }
    }
}
