//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.VatTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblKyhieudonvidathang
    {
        public string MADV { get; set; }
        public string Kyhieudonvi { get; set; }
        public string Kihieucoso { get; set; }
        public string Kyhieudonvidathang { get; set; }
    }
}
