//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.VatTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNhomVattu
    {
        public string Manhom { get; set; }
        public string Tenmanhom { get; set; }
        public Nullable<bool> Hieuluc { get; set; }
        public Nullable<System.DateTime> Ngaycapnhat { get; set; }
        public string Manvcapnhat { get; set; }
        public Nullable<System.DateTime> Ngaymodify { get; set; }
        public string Manvmodify { get; set; }
    }
}
