//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.VatTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLTHUKYBANTGD
    {
        public string KYHIEUDONVI { get; set; }
        public string MAPD { get; set; }
        public string MATIEPNHAN { get; set; }
        public string EMAILTHUKY { get; set; }
    }
}
