//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.VatTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiGia
    {
        public int Id { get; set; }
        public string CurrencyCode { get; set; }
        public string CurrencyName { get; set; }
        public Nullable<double> Buy { get; set; }
        public Nullable<double> Transfer { get; set; }
        public Nullable<double> Sell { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
    }
}
