//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.VatTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class TONDAUKY
    {
        public string Nam { get; set; }
        public string MaVT { get; set; }
        public string MaKho { get; set; }
        public Nullable<decimal> SLTonDauKy { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public string MaPhieuPD { get; set; }
        public string Khoa { get; set; }
        public string LoaiVT { get; set; }
        public string DonviSDung { get; set; }
        public Nullable<decimal> Dongia { get; set; }
        public Nullable<decimal> Den170918conton { get; set; }
    
        public virtual DMKHo DMKHo { get; set; }
        public virtual DANHMUCVATTU DANHMUCVATTU { get; set; }
    }
}
