//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.VatTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class TongCPtheoMH
    {
        public string idkhoa { get; set; }
        public string MahangD { get; set; }
        public string MahangN { get; set; }
        public string nguongoc { get; set; }
        public Nullable<decimal> CPnhuom { get; set; }
        public Nullable<decimal> CPDet { get; set; }
        public Nullable<decimal> CPLuuthong { get; set; }
        public Nullable<decimal> Tigia { get; set; }
        public Nullable<decimal> loinhuan { get; set; }
        public Nullable<decimal> giaban { get; set; }
        public Nullable<decimal> GiaVon { get; set; }
        public Nullable<System.DateTime> Ngaytinh { get; set; }
        public string MaPhieuTT { get; set; }
        public Nullable<decimal> CPDet_ChuyenLai { get; set; }
        public Nullable<decimal> CPLuuthong_ChuyenLai { get; set; }
        public Nullable<decimal> giaban_ChuyenLai { get; set; }
        public Nullable<decimal> GiaVon_ChuyenLai { get; set; }
    }
}
