//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.VatTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class TongHopTDK
    {
        public string Nam { get; set; }
        public string MaVT { get; set; }
        public Nullable<decimal> SLTonDauKy { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
    }
}
