//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.VatTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTchitietnhanTT
    {
        public string MaphieuTT { get; set; }
        public string ManvNhan { get; set; }
        public string MaBP { get; set; }
        public string Chucvu { get; set; }
        public string LoaiTT { get; set; }
    }
}
