//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.VatTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTCHIPHICHATLUONG
    {
        public string KHOACPCL { get; set; }
        public string THITRUONG { get; set; }
        public decimal TILE { get; set; }
        public Nullable<bool> HIEULUC { get; set; }
        public Nullable<System.DateTime> NGAYCN { get; set; }
        public string NGUOICAPNHAT { get; set; }
    }
}
