//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.VatTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTCHIPHIVANCHUYEN
    {
        public string KHOACPVC { get; set; }
        public string THITRUONG { get; set; }
        public Nullable<decimal> DonGiaCont { get; set; }
        public Nullable<decimal> SanLuongCont { get; set; }
        public decimal DONGIA { get; set; }
        public string DVT { get; set; }
        public Nullable<System.DateTime> NGAYCN { get; set; }
        public Nullable<bool> HIEULUC { get; set; }
        public string NVCAPNHAT { get; set; }
    }
}
