//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.VatTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTCTPHIEUMAHANG_EXCEL
    {
        public string Mahang { get; set; }
        public string Capmau { get; set; }
        public string Tone1 { get; set; }
        public int Tone { get; set; }
        public string Phuongthuc { get; set; }
        public string Kho { get; set; }
        public string Macongnghenhuom { get; set; }
        public string Uudai { get; set; }
        public string LoaiHang { get; set; }
        public string Loai { get; set; }
        public string NGUOICAPNHAT { get; set; }
        public Nullable<System.DateTime> NGAYCAPNHAT { get; set; }
    }
}
