//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.VatTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTDMBaoBi
    {
        public string Ma { get; set; }
        public string ten { get; set; }
        public string loaihang { get; set; }
        public string Kho { get; set; }
        public string thitrongdongkieu { get; set; }
        public string dvt { get; set; }
        public Nullable<decimal> tien { get; set; }
        public string ghichu { get; set; }
        public Nullable<long> Hieuluc { get; set; }
        public Nullable<System.DateTime> Ngaycn { get; set; }
        public string ThiTruong { get; set; }
        public string manvxk { get; set; }
        public string manvkt { get; set; }
    }
}
