//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.VatTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTG_BASEVN_TOKEN_API
    {
        public string namebase { get; set; }
        public string access_token { get; set; }
        public string service_id { get; set; }
        public string block_id { get; set; }
        public string username { get; set; }
        public string url { get; set; }
        public int id_log { get; set; }
        public Nullable<bool> isHieuluc { get; set; }
    }
}
