//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.VatTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTG_BASEVN_LOG_PR
    {
        public string MAPHIEUPR { get; set; }
        public Nullable<bool> isSTATUS { get; set; }
        public string STATUSCODE { get; set; }
        public string Department { get; set; }
        public string ERROR { get; set; }
        public string GHICHU { get; set; }
        public int ID_LOG { get; set; }
        public Nullable<System.DateTime> NGAYCN { get; set; }
        public string Root_id { get; set; }
    }
}
