//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.VatTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTG_BASEVN_DEPARTMENT
    {
        public string BASE_DEPARTMENT { get; set; }
        public string KIHIEU { get; set; }
        public int ID_LOG { get; set; }
    }
}
