//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.VatTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTLuuChiPhiBaoBi
    {
        public string idkhoa { get; set; }
        public string Ma { get; set; }
        public Nullable<decimal> tien { get; set; }
        public string ten { get; set; }
        public Nullable<decimal> thanhtien_baobi { get; set; }
    }
}
