//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.VatTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTPhanhoi
    {
        public string MaphieuTT { get; set; }
        public string Macd1 { get; set; }
        public string Macd2 { get; set; }
        public int idkhoa { get; set; }
    }
}
