//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.VatTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class VATTU2024_DMKHO
    {
        public string MAKHO { get; set; }
        public string TENKHO { get; set; }
        public string MAKHOKETOAN { get; set; }
        public string NHOM_OGSTM { get; set; }
        public string DV_OGSTM { get; set; }
        public string DIACHI { get; set; }
        public Nullable<bool> XUATNOIBO { get; set; }
        public string ThuKho { get; set; }
        public string Loaiphieu { get; set; }
        public Nullable<bool> hieuluc { get; set; }
        public Nullable<bool> IsNhamay { get; set; }
    }
}
