//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.VatTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class VATTU2026_CTPHIEU_MAVTTUONGDUONG
    {
        public string KEY_CTPHIEU { get; set; }
        public string MAVT { get; set; }
        public string MAVT_TDUONG { get; set; }
        public Nullable<decimal> GIANHAPGANNHAT { get; set; }
        public string GHICHU { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public int KEYID { get; set; }
        public string MAPHIEU { get; set; }
    }
}
