//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.KhoTP2023
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QUANLYKHOTP2023Entities : DbContext
    {
        public QUANLYKHOTP2023Entities()
            : base("name=QUANLYKHOTP2023Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<TONKHO290224_IAA_Adjustments_Result> TONKHO290224_IAA_Adjustments(string lOCATION, string key, string thang)
        {
            var lOCATIONParameter = lOCATION != null ?
                new ObjectParameter("LOCATION", lOCATION) :
                new ObjectParameter("LOCATION", typeof(string));
    
            var keyParameter = key != null ?
                new ObjectParameter("Key", key) :
                new ObjectParameter("Key", typeof(string));
    
            var thangParameter = thang != null ?
                new ObjectParameter("thang", thang) :
                new ObjectParameter("thang", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TONKHO290224_IAA_Adjustments_Result>("TONKHO290224_IAA_Adjustments", lOCATIONParameter, keyParameter, thangParameter);
        }
    
        public virtual ObjectResult<TONKHO290224_IAA_InventoryDetail_Result> TONKHO290224_IAA_InventoryDetail(string lOCATION, string key, string thang)
        {
            var lOCATIONParameter = lOCATION != null ?
                new ObjectParameter("LOCATION", lOCATION) :
                new ObjectParameter("LOCATION", typeof(string));
    
            var keyParameter = key != null ?
                new ObjectParameter("Key", key) :
                new ObjectParameter("Key", typeof(string));
    
            var thangParameter = thang != null ?
                new ObjectParameter("thang", thang) :
                new ObjectParameter("thang", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TONKHO290224_IAA_InventoryDetail_Result>("TONKHO290224_IAA_InventoryDetail", lOCATIONParameter, keyParameter, thangParameter);
        }
    
        public virtual ObjectResult<TONKHO290224_InventoryAdjustment_Result> TONKHO290224_InventoryAdjustment(string lOCATION, string key, string thang)
        {
            var lOCATIONParameter = lOCATION != null ?
                new ObjectParameter("LOCATION", lOCATION) :
                new ObjectParameter("LOCATION", typeof(string));
    
            var keyParameter = key != null ?
                new ObjectParameter("Key", key) :
                new ObjectParameter("Key", typeof(string));
    
            var thangParameter = thang != null ?
                new ObjectParameter("thang", thang) :
                new ObjectParameter("thang", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TONKHO290224_InventoryAdjustment_Result>("TONKHO290224_InventoryAdjustment", lOCATIONParameter, keyParameter, thangParameter);
        }
    }
}
