//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.NetsuiteTT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chart_of_Accounts
    {
        public string InternalID_NS { get; set; }
        public string Number_TT { get; set; }
        public string Externalid_NS { get; set; }
        public int @int { get; set; }
    }
}
