//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.NetsuiteTT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        public string externalid { get; set; }
        public string name { get; set; }
        public string parent { get; set; }
        public string tbl_franchise { get; set; }
        public string code_Department { get; set; }
        public string Desciption { get; set; }
    }
}
