//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.NetsuiteTT
{
    using System;
    using System.Collections.Generic;
    
    public partial class DongBoVATTU_SOI__Json_Log
    {
        public int Id { get; set; }
        public string Id_Json { get; set; }
        public string Source { get; set; }
        public string JsonNotification { get; set; }
        public Nullable<bool> Error { get; set; }
        public string Action { get; set; }
        public string PhanLoai { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public string MayTinh { get; set; }
        public string Type { get; set; }
    }
}
