//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.NetsuiteTT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donvi_mapping_Department_bk150424
    {
        public string internalid { get; set; }
        public string externalid { get; set; }
        public string name { get; set; }
        public string parent { get; set; }
        public string idmadv { get; set; }
        public string madv { get; set; }
        public string idmacs { get; set; }
        public string mabp { get; set; }
        public string Account_Donvi_Xsudung { get; set; }
        public string donvidathang { get; set; }
        public string ghichu { get; set; }
    }
}
