//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.NetsuiteTT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expense_Code
    {
        public string Internalid_ExpenseCode { get; set; }
        public string Externalid_ExpenseCode { get; set; }
        public string Name_code { get; set; }
        public string Expense_code1 { get; set; }
        public string CP_NguoiLaoDong { get; set; }
        public string Department { get; set; }
        public string Acount_Chiphi_SX { get; set; }
        public int stt { get; set; }
    }
}
