//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.NetsuiteTT
{
    using System;
    using System.Collections.Generic;
    
    public partial class GhiLog_DMVattu_ErrorAPI_NS
    {
        public string Internalid { get; set; }
        public string Externalid { get; set; }
        public string MAVT { get; set; }
        public string TenVT { get; set; }
        public string DVT { get; set; }
        public string LogNS { get; set; }
        public System.Guid id { get; set; }
        public string MANV { get; set; }
        public Nullable<System.DateTime> Ngaylog { get; set; }
        public string HanhDong { get; set; }
    }
}
