//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.NetsuiteTT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kho
    {
        public int STT { get; set; }
        public string externalid { get; set; }
        public string name { get; set; }
        public string parent { get; set; }
        public string makho { get; set; }
        public string tenkho { get; set; }
        public string loai { get; set; }
        public string ID_nhamaysx { get; set; }
        public string IDMADV { get; set; }
        public string NHAMAY { get; set; }
    }
}
