//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.NetsuiteTT
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiSanPhamChiTiet
    {
        public string externalid { get; set; }
        public string Name { get; set; }
        public string MaLoaiSPCT { get; set; }
        public string PhanNhomSanPham { get; set; }
        public string Kytu1 { get; set; }
        public string MoTa { get; set; }
    }
}
