//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.NetsuiteTT
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiYeuCauSanXuat
    {
        public string Internalid_LoaiYCSX { get; set; }
        public string Name_Loai { get; set; }
        public Nullable<bool> GC_SOI { get; set; }
    }
}
