//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.NetsuiteTT
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class NetsuiteTTEntities1 : DbContext
    {
        public NetsuiteTTEntities1()
            : base("name=NetsuiteTTEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BongIn> BongIns { get; set; }
        public virtual DbSet<BongNenVai> BongNenVais { get; set; }
        public virtual DbSet<BTM_Serial_No_List> BTM_Serial_No_List { get; set; }
        public virtual DbSet<CaDet> CaDets { get; set; }
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<CongNgheDet> CongNgheDets { get; set; }
        public virtual DbSet<DongBoVATTU_SOI__Json_Log> DongBoVATTU_SOI__Json_Log { get; set; }
        public virtual DbSet<Donvi_mapping_Department> Donvi_mapping_Department { get; set; }
        public virtual DbSet<DonViTienTe> DonViTienTes { get; set; }
        public virtual DbSet<DSInvoiceXuatKhau> DSInvoiceXuatKhaus { get; set; }
        public virtual DbSet<DSPhieuUploadN> DSPhieuUploadNS { get; set; }
        public virtual DbSet<DSPhieuViPhamEntity> DSPhieuViPhamEntities { get; set; }
        public virtual DbSet<DSPhieuViPhamQuantityItem> DSPhieuViPhamQuantityItems { get; set; }
        public virtual DbSet<DSPhieuViPhamSerialLotNumber> DSPhieuViPhamSerialLotNumbers { get; set; }
        public virtual DbSet<Expense_Code> Expense_Code { get; set; }
        public virtual DbSet<GhiLog_DMVattu_ErrorAPI_NS> GhiLog_DMVattu_ErrorAPI_NS { get; set; }
        public virtual DbSet<KenhPhanPhoi> KenhPhanPhois { get; set; }
        public virtual DbSet<Kho> Khoes { get; set; }
        public virtual DbSet<KhoanMucChiPhi> KhoanMucChiPhis { get; set; }
        public virtual DbSet<KhoVai> KhoVais { get; set; }
        public virtual DbSet<KichCo> KichCoes { get; set; }
        public virtual DbSet<LoaiGiaBan> LoaiGiaBans { get; set; }
        public virtual DbSet<LoaiKhachHang> LoaiKhachHangs { get; set; }
        public virtual DbSet<LoaiMayDet> LoaiMayDets { get; set; }
        public virtual DbSet<LoaiNhaCungCap> LoaiNhaCungCaps { get; set; }
        public virtual DbSet<LoaiSanPham> LoaiSanPhams { get; set; }
        public virtual DbSet<LoaiSanPhamChiTiet> LoaiSanPhamChiTiets { get; set; }
        public virtual DbSet<LoaiVatTu> LoaiVatTus { get; set; }
        public virtual DbSet<LoaiYeuCau> LoaiYeuCaus { get; set; }
        public virtual DbSet<LoaiYeuCauSanXuat> LoaiYeuCauSanXuats { get; set; }
        public virtual DbSet<NguocGoc> NguocGocs { get; set; }
        public virtual DbSet<NguonHangSanXuat> NguonHangSanXuats { get; set; }
        public virtual DbSet<NhomHang> NhomHangs { get; set; }
        public virtual DbSet<NhomHoaVanDetIn> NhomHoaVanDetIns { get; set; }
        public virtual DbSet<NhomMucDichSuDung> NhomMucDichSuDungs { get; set; }
        public virtual DbSet<NhomSanPham> NhomSanPhams { get; set; }
        public virtual DbSet<NhomSanPhamKinhDoanh> NhomSanPhamKinhDoanhs { get; set; }
        public virtual DbSet<NhomSoi> NhomSois { get; set; }
        public virtual DbSet<NhomTrangPhuc> NhomTrangPhucs { get; set; }
        public virtual DbSet<PhanLoaiSPMay> PhanLoaiSPMays { get; set; }
        public virtual DbSet<PhanNhomSanPham> PhanNhomSanPhams { get; set; }
        public virtual DbSet<PhuongThucThanhToan> PhuongThucThanhToans { get; set; }
        public virtual DbSet<SaleOrder_Viseri> SaleOrder_Viseri { get; set; }
        public virtual DbSet<SaleOrder_Viseri_Item> SaleOrder_Viseri_Item { get; set; }
        public virtual DbSet<Table_LoaiPhieuVanChuyenNoiBo> Table_LoaiPhieuVanChuyenNoiBo { get; set; }
        public virtual DbSet<Table_Mapping_DinhMuc_KeyHH_MOC> Table_Mapping_DinhMuc_KeyHH_MOC { get; set; }
        public virtual DbSet<Table_Mapping_MACP_TenVT_Dinhmucdet> Table_Mapping_MACP_TenVT_Dinhmucdet { get; set; }
        public virtual DbSet<Table_Mapping_MACP_TenVT_DinhmuctheuddaA_Z> Table_Mapping_MACP_TenVT_DinhmuctheuddaA_Z { get; set; }
        public virtual DbSet<Table_Mapping_MaHangSPM_MaKieuDang> Table_Mapping_MaHangSPM_MaKieuDang { get; set; }
        public virtual DbSet<Table_Mapping_Mavattu_DVT> Table_Mapping_Mavattu_DVT { get; set; }
        public virtual DbSet<Table_TAX_CODE> Table_TAX_CODE { get; set; }
        public virtual DbSet<TaiKhoanNhanVien_Netsuite> TaiKhoanNhanVien_Netsuite { get; set; }
        public virtual DbSet<TBL_Mapping_DoiTuongKhachHang_Customers> TBL_Mapping_DoiTuongKhachHang_Customers { get; set; }
        public virtual DbSet<Tbl_Mapping_NguonGocSP_ThuongHieu> Tbl_Mapping_NguonGocSP_ThuongHieu { get; set; }
        public virtual DbSet<TenHopQui> TenHopQuis { get; set; }
        public virtual DbSet<ThiTruongXuatKhau> ThiTruongXuatKhaus { get; set; }
        public virtual DbSet<Chart_of_Accounts> Chart_of_Accounts { get; set; }
        public virtual DbSet<Donvi_mapping_Department_bk150424> Donvi_mapping_Department_bk150424 { get; set; }
        public virtual DbSet<GioiTinh> GioiTinhs { get; set; }
        public virtual DbSet<kho_bk_30052024> kho_bk_30052024 { get; set; }
        public virtual DbSet<KhuVuc> KhuVucs { get; set; }
        public virtual DbSet<OtherChagreForPurchase> OtherChagreForPurchases { get; set; }
        public virtual DbSet<Table_Mapping_Mavattu_DVT_BK_23032024> Table_Mapping_Mavattu_DVT_BK_23032024 { get; set; }
        public virtual DbSet<TBL_Data_BCChiPhiVatTu_BC14> TBL_Data_BCChiPhiVatTu_BC14 { get; set; }
    
        public virtual ObjectResult<VATTU2024_SP_LOAD_ExpenseCodeList_Result> VATTU2024_SP_LOAD_ExpenseCodeList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VATTU2024_SP_LOAD_ExpenseCodeList_Result>("VATTU2024_SP_LOAD_ExpenseCodeList");
        }
    
        public virtual ObjectResult<SPLOAD_TONKHOALL_TP_2024_Result> SPLOAD_TONKHOALL_TP_2024()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPLOAD_TONKHOALL_TP_2024_Result>("SPLOAD_TONKHOALL_TP_2024");
        }
    
        public virtual ObjectResult<VATTU2024_LOAD_LOAISPCHITIET_Result> VATTU2024_LOAD_LOAISPCHITIET(string mAVT)
        {
            var mAVTParameter = mAVT != null ?
                new ObjectParameter("MAVT", mAVT) :
                new ObjectParameter("MAVT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VATTU2024_LOAD_LOAISPCHITIET_Result>("VATTU2024_LOAD_LOAISPCHITIET", mAVTParameter);
        }
    }
}
