//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.NetsuiteTT
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguocGoc
    {
        public string Externalid { get; set; }
        public string Name { get; set; }
        public string MaNguonGoc { get; set; }
        public string ChonHayNhapHang { get; set; }
        public string ThiTruong { get; set; }
        public string PhienMaDonHangNhuomIn { get; set; }
        public string GhiChu { get; set; }
    }
}
