//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.NetsuiteTT
{
    using System;
    using System.Collections.Generic;
    
    public partial class OtherChagreForPurchase
    {
        public string ExternalID { get; set; }
        public string Name { get; set; }
        public string DisplayName { get; set; }
        public Nullable<decimal> ExpenseCogsAccount { get; set; }
        public Nullable<bool> UsedByBTMMCSuiteApp { get; set; }
        public string WipStatus { get; set; }
    }
}
