//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.NetsuiteTT
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanNhomSanPham
    {
        public string externalid { get; set; }
        public string MaLoaiSP { get; set; }
        public string MaLoaiSP_TT { get; set; }
        public string LoaiSanPham_NS { get; set; }
        public string NameSP { get; set; }
        public string KyTu { get; set; }
        public string LoaiVT_TT { get; set; }
        public int STT { get; set; }
        public Nullable<bool> hieuluc { get; set; }
    }
}
