//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.NetsuiteTT
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanLoaiSPMay
    {
        public string Externalid_NhomSPM { get; set; }
        public string Name_NS { get; set; }
        public string Name_TT { get; set; }
        public string ID_TT { get; set; }
        public string KyTu1 { get; set; }
    }
}
