//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.NetsuiteTT
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleOrder_Viseri_Item
    {
        public string MaDonHang { get; set; }
        public string MaVatTuKH { get; set; }
        public string TenVatTu { get; set; }
        public string DVT { get; set; }
        public Nullable<decimal> SLKhachGiao { get; set; }
        public string MaCongDoan { get; set; }
        public string DinhMucGM { get; set; }
        public string LyDoNhan { get; set; }
        public string NgCapNhat { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public string NgDieuChinh { get; set; }
        public Nullable<System.DateTime> NgayDieuChinh { get; set; }
        public System.Guid ID_Khoa { get; set; }
    }
}
