//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.NetsuiteTT
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleOrder_Viseri
    {
        public string SoHD { get; set; }
        public System.DateTime NgayHD { get; set; }
        public string MaDonHang { get; set; }
        public Nullable<System.DateTime> NgayDonHang { get; set; }
        public string LoaiDonHang { get; set; }
        public string HinhThuGiaCong { get; set; }
        public string LoaiGC { get; set; }
        public string MaDonViNhan { get; set; }
        public string MaKhoNhan { get; set; }
        public string KhachHang { get; set; }
        public string QuocGia { get; set; }
        public string ThiTruong { get; set; }
        public string DonGia { get; set; }
        public string DonViTinhGia { get; set; }
        public Nullable<decimal> TyGia { get; set; }
        public string MaHangThanhPham { get; set; }
        public Nullable<decimal> TongSLKhachGiao { get; set; }
        public Nullable<decimal> SLThanhPhamDuKien { get; set; }
        public string DVT { get; set; }
        public string DinhMucGM { get; set; }
        public string TieuHaoVoHinh { get; set; }
        public string TieuHaoHuuHinh { get; set; }
        public string DVTTieuHao { get; set; }
        public Nullable<System.DateTime> NgayDuKienGiaoHang { get; set; }
        public string NguoiCN { get; set; }
        public string NgayCN { get; set; }
        public string NguoiDC { get; set; }
        public Nullable<System.DateTime> NgayDC { get; set; }
        public Nullable<bool> KetThucDonHang { get; set; }
        public string NguoiKTDH { get; set; }
        public Nullable<System.DateTime> NgayKTDH { get; set; }
    }
}
