//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.NetsuiteTT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Mapping_MaHangSPM_MaKieuDang
    {
        public string Externalid_MaKieuDang { get; set; }
        public string ID_TT { get; set; }
        public string Name { get; set; }
        public string LOAISP { get; set; }
        public string Externalid_NhomMDSD { get; set; }
        public string Externalid_LoaiSPMay { get; set; }
    }
}
