//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.NetsuiteTT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_TAX_CODE
    {
        public string Internalid_taxcode { get; set; }
        public string Name_Tax_code { get; set; }
        public string Desciption { get; set; }
        public string Rate { get; set; }
        public Nullable<bool> HieuLuc { get; set; }
        public int STT { get; set; }
    }
}
