//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.NetsuiteTT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Mapping_Mavattu_DVT
    {
        public string Internalid { get; set; }
        public string Externalid { get; set; }
        public string DVT { get; set; }
        public string TenDVT { get; set; }
        public int stt { get; set; }
    }
}
