//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.NetsuiteTT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_LoaiPhieuVanChuyenNoiBo
    {
        public string InternalID { get; set; }
        public string ExternalID { get; set; }
        public string Name { get; set; }
        public string LoaiPhieu { get; set; }
        public int STT { get; set; }
    }
}
