//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.NetsuiteTT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Mapping_MACP_TenVT_Dinhmucdet
    {
        public string MACP { get; set; }
        public string Ten { get; set; }
        public string MAPPING_KYHIEUCP { get; set; }
        public int INT { get; set; }
    }
}
