//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.NetsuiteTT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Mapping_DinhMuc_KeyHH_MOC
    {
        public string Internalid_BOM_Rev { get; set; }
        public string KeyHH { get; set; }
        public string IDChiPhi { get; set; }
        public int STT { get; set; }
        public string Internalid_BOM { get; set; }
        public string SoLanTinh_KeyHH { get; set; }
    }
}
