//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.NetsuiteTT
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Data_BCChiPhiVatTu_BC14
    {
        public string Item { get; set; }
        public string ItemName { get; set; }
        public string SoPhieu { get; set; }
        public Nullable<System.DateTime> NgayPhieu { get; set; }
        public string Location { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> SoTienNo { get; set; }
        public Nullable<decimal> SoTienCo { get; set; }
        public string Account { get; set; }
        public string AccountMain { get; set; }
        public string Memo { get; set; }
        public Nullable<System.DateTime> NgayCN { get; set; }
        public string MANVCN { get; set; }
        public System.Guid ID_ { get; set; }
        public string PhongBan { get; set; }
        public string KeToanKiemTra { get; set; }
        public string Type { get; set; }
    }
}
