//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.NetsuiteTT
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Mapping_DoiTuongKhachHang_Customers
    {
        public int STT { get; set; }
        public string ExternalID_CUSTOMER { get; set; }
        public string Showroom { get; set; }
        public string MaLoaiKhachHang { get; set; }
        public string MaDoiTuongKH { get; set; }
        public string DoiTuong { get; set; }
        public string DiaChi { get; set; }
        public string MST { get; set; }
        public string NguoiDaiDien { get; set; }
        public string SoDienThoai { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> NgayMuaHangDauTien { get; set; }
        public string CMND { get; set; }
        public Nullable<System.DateTime> NgayCap { get; set; }
        public string NoiCap { get; set; }
        public string SoTaiKhoan { get; set; }
        public string Nganhang { get; set; }
        public string ThiTruong { get; set; }
        public string NhanVienQuanLy { get; set; }
        public string KenhPP { get; set; }
        public string KhuVuc { get; set; }
        public string SanPham { get; set; }
        public Nullable<bool> HieuLuc { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string LastModifiedByID { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public string DonViPhuTrach { get; set; }
        public string BH_KT { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string Ghichu { get; set; }
        public Nullable<bool> GuiAPI { get; set; }
        public Nullable<System.DateTime> NgayGuiAPI { get; set; }
    }
}
