//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.GiaThanhSPM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class GiaThanh_SPMEntities : DbContext
    {
        public GiaThanh_SPMEntities()
            : base("name=GiaThanh_SPMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<GET_MAMH_TAO_PR_SPM_Result> GET_MAMH_TAO_PR_SPM(string mADH)
        {
            var mADHParameter = mADH != null ?
                new ObjectParameter("MADH", mADH) :
                new ObjectParameter("MADH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_MAMH_TAO_PR_SPM_Result>("GET_MAMH_TAO_PR_SPM", mADHParameter);
        }
    }
}
