//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.DonHang09
{
    using System;
    using System.Collections.Generic;
    
    public partial class CN_DONHANG
    {
        public string MADH_CN { get; set; }
        public string MAKHACHHANG { get; set; }
        public string SOHOPDONG { get; set; }
        public string LOAIHOPDONG { get; set; }
        public string THITRUONG { get; set; }
        public string MANVDATHANG { get; set; }
        public Nullable<decimal> TSOMETDH { get; set; }
        public string PHUONGTHUC { get; set; }
        public string MADV_SX { get; set; }
        public string LOAIHINHKINHDOANH { get; set; }
        public string LOAIDICHVU { get; set; }
        public Nullable<decimal> GM_CHOPHEP { get; set; }
        public Nullable<decimal> GM_DONHANG { get; set; }
        public Nullable<bool> BANTGD_DUYET { get; set; }
        public string MANVCN { get; set; }
        public Nullable<System.DateTime> NGAYCN { get; set; }
        public Nullable<bool> HIEULUC { get; set; }
        public string GHICHU_DONVIDAT { get; set; }
        public string MANV_XEMXET { get; set; }
        public Nullable<System.DateTime> NGAY_XEMXET { get; set; }
        public Nullable<bool> HIEULUC_XEMXET { get; set; }
        public string MANV_TIEPNHAN_CU { get; set; }
        public Nullable<System.DateTime> NGAY_TIEPNHAN_CU { get; set; }
        public Nullable<bool> HIEULUC_TIEPNHAN_CU { get; set; }
        public string MANV_TIEPNHAN_QA { get; set; }
        public Nullable<System.DateTime> NGAY_TIEPNHAN_QA { get; set; }
        public Nullable<bool> HIEULUC_TIEPNHAN_QA { get; set; }
        public string MANV_TIEPNHAN_NMN { get; set; }
        public Nullable<System.DateTime> NGAY_TIEPNHAN_NMN { get; set; }
        public Nullable<bool> HIEULUC_TIEPNHAN_NMN { get; set; }
        public string MANV_TIEPNHAN_NMMAY { get; set; }
        public Nullable<System.DateTime> NGAY_TIEPNHAN_NMMAY { get; set; }
        public Nullable<bool> HIEULUC_TIEPNHAN_NMMAY { get; set; }
    }
}
