//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.DonHang09
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QLDonHang09Entities : DbContext
    {
        public QLDonHang09Entities()
            : base("name=QLDonHang09Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CN_DONHANG> CN_DONHANG { get; set; }
    
        public virtual ObjectResult<GET_SODONHANG_Result> GET_SODONHANG()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_SODONHANG_Result>("GET_SODONHANG");
        }
    
        public virtual ObjectResult<API_DinhmucDet_SOI_CONGDOAN_Result> API_DinhmucDet_SOI_CONGDOAN(string thang, string nam)
        {
            var thangParameter = thang != null ?
                new ObjectParameter("thang", thang) :
                new ObjectParameter("thang", typeof(string));
    
            var namParameter = nam != null ?
                new ObjectParameter("nam", nam) :
                new ObjectParameter("nam", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<API_DinhmucDet_SOI_CONGDOAN_Result>("API_DinhmucDet_SOI_CONGDOAN", thangParameter, namParameter);
        }
    
        public virtual ObjectResult<Load_QuocGia_Result> Load_QuocGia()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Load_QuocGia_Result>("Load_QuocGia");
        }
    
        public virtual ObjectResult<load_TBLKHACHHANG_Result> load_TBLKHACHHANG(string makhachhang, string quocgia)
        {
            var makhachhangParameter = makhachhang != null ?
                new ObjectParameter("makhachhang", makhachhang) :
                new ObjectParameter("makhachhang", typeof(string));
    
            var quocgiaParameter = quocgia != null ?
                new ObjectParameter("quocgia", quocgia) :
                new ObjectParameter("quocgia", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<load_TBLKHACHHANG_Result>("load_TBLKHACHHANG", makhachhangParameter, quocgiaParameter);
        }
    }
}
